var shadow$provide = {};
(function(){
'use strict';var f;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function t(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"}var aa="closure_uid_"+(1E9*Math.random()>>>0),ba=0;function da(a){const b=[];let c=0;for(const d in a)b[c++]=d;return b};function ea(a,b){null!=a&&this.append.apply(this,arguments)}f=ea.prototype;f.Ba="";f.set=function(a){this.Ba=""+a};f.append=function(a,b,c){this.Ba+=String(a);if(null!=b)for(let d=1;d<arguments.length;d++)this.Ba+=arguments[d];return this};f.clear=function(){this.Ba=""};f.toString=function(){return this.Ba};var v={},fa=null;function w(a){return null!=a&&!1!==a}function ha(a){return a instanceof Array}function x(a,b){return a[t(null==b?null:b)]?!0:a._?!0:!1}function y(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",w(w(c)?c.Kb:c)?c.pb:t(b),": ",b].join(""))}function ia(a){var b=a.pb;return w(b)?b:A.g(a)}var ja="undefined"!==typeof Symbol&&"function"===t(Symbol)?Symbol.iterator:"@@iterator";
function C(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}function ka(){}function la(a){if(null!=a&&null!=a.U)a=a.U(a);else{var b=la[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=la._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("ICounted.-count",a);}return a}function ma(){}
function na(a){if(null!=a&&null!=a.V)a=a.V(a);else{var b=na[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=na._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IEmptyableCollection.-empty",a);}return a}function oa(a,b){if(null!=a&&null!=a.T)a=a.T(a,b);else{var c=oa[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=oa._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("ICollection.-conj",a);}return a}function pa(){}
var qa=function(){function a(d,e,g){var h=D[t(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);h=D._;if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);throw y("IIndexed.-nth",d);}function b(d,e){var g=D[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=D._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw y("IIndexed.-nth",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),D=function D(a){switch(arguments.length){case 2:return D.h(arguments[0],arguments[1]);case 3:return D.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}};D.h=function(a,b){return null!=a&&null!=a.W?a.W(a,b):qa(a,b)};D.l=function(a,b,c){return null!=a&&null!=a.la?a.la(a,b,c):qa(a,b,c)};D.ga=3;
function E(a){if(null!=a&&null!=a.aa)a=a.aa(a);else{var b=E[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=E._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("ISeq.-first",a);}return a}function G(a){if(null!=a&&null!=a.fa)a=a.fa(a);else{var b=G[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=G._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("ISeq.-rest",a);}return a}function ra(){}function sa(){}
var ua=function(){function a(d,e,g){var h=ta[t(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);h=ta._;if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);throw y("ILookup.-lookup",d);}function b(d,e){var g=ta[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=ta._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw y("ILookup.-lookup",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),ta=function ta(a){switch(arguments.length){case 2:return ta.h(arguments[0],arguments[1]);case 3:return ta.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}};ta.h=function(a,b){return null!=a&&null!=a.ka?a.ka(a,b):ua(a,b)};ta.l=function(a,b,c){return null!=a&&null!=a.H?a.H(a,b,c):ua(a,b,c)};ta.ga=3;function va(){}
function wa(a,b){if(null!=a&&null!=a.Ua)a=a.Ua(a,b);else{var c=wa[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=wa._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IAssociative.-contains-key?",a);}return a}function xa(a,b,c){if(null!=a&&null!=a.xa)a=a.xa(a,b,c);else{var d=xa[t(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=xa._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw y("IAssociative.-assoc",a);}return a}function za(){}
function Aa(a){if(null!=a&&null!=a.Eb)a=a.key;else{var b=Aa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Aa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IMapEntry.-key",a);}return a}function Ba(a){if(null!=a&&null!=a.Fb)a=a.G;else{var b=Ba[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Ba._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IMapEntry.-val",a);}return a}function Ca(){}
function Da(a){if(null!=a&&null!=a.Ab)a=a.G;else{var b=Da[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Da._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IDeref.-deref",a);}return a}function Ea(){}function Fa(a){if(null!=a&&null!=a.O)a=a.O(a);else{var b=Fa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Fa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IMeta.-meta",a);}return a}
function Ga(a,b){if(null!=a&&null!=a.P)a=a.P(a,b);else{var c=Ga[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ga._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IWithMeta.-with-meta",a);}return a}function Ha(){}
var Ja=function(){function a(d,e,g){var h=Ia[t(null==d?null:d)];if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);h=Ia._;if(null!=h)return h.l?h.l(d,e,g):h.call(null,d,e,g);throw y("IReduce.-reduce",d);}function b(d,e){var g=Ia[t(null==d?null:d)];if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);g=Ia._;if(null!=g)return g.h?g.h(d,e):g.call(null,d,e);throw y("IReduce.-reduce",d);}var c=null;c=function(d,e,g){switch(arguments.length){case 2:return b.call(this,d,e);case 3:return a.call(this,d,e,g)}throw Error("Invalid arity: "+
arguments.length);};c.h=b;c.l=a;return c}(),Ia=function Ia(a){switch(arguments.length){case 2:return Ia.h(arguments[0],arguments[1]);case 3:return Ia.l(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}};Ia.h=function(a,b){return null!=a&&null!=a.Z?a.Z(a,b):Ja(a,b)};Ia.l=function(a,b,c){return null!=a&&null!=a.$?a.$(a,b,c):Ja(a,b,c)};Ia.ga=3;function Ka(){}
function La(a,b){if(null!=a&&null!=a.hb)a=a.hb(a,b,!0);else{var c=La[t(null==a?null:a)];if(null!=c)a=c.l?c.l(a,b,!0):c.call(null,a,b,!0);else if(c=La._,null!=c)a=c.l?c.l(a,b,!0):c.call(null,a,b,!0);else throw y("IKVReduce.-kv-reduce",a);}return a}function Ma(a,b){if(null!=a&&null!=a.J)a=a.J(a,b);else{var c=Ma[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Ma._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IEquiv.-equiv",a);}return a}
function Na(a){if(null!=a&&null!=a.N)a=a.N(a);else{var b=Na[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Na._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IHash.-hash",a);}return a}function Oa(){}function Pa(a){if(null!=a&&null!=a.I)a=a.I(a);else{var b=Pa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Pa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("ISeqable.-seq",a);}return a}function Qa(){}function Ra(){}function Sa(){}
function H(a,b){if(null!=a&&null!=a.vb)a=a.vb(a,b);else{var c=H[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=H._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("IWriter.-write",a);}return a}function Ta(){}function Ua(a,b,c){if(null!=a&&null!=a.K)a=a.K(a,b,c);else{var d=Ua[t(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=Ua._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw y("IPrintWithWriter.-pr-writer",a);}return a}
function Va(a){if(null!=a&&null!=a.Xa)a=a.Xa(a);else{var b=Va[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Va._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IEditableCollection.-as-transient",a);}return a}function Wa(a,b){if(null!=a&&null!=a.$a)a=a.$a(a,b);else{var c=Wa[t(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=Wa._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw y("ITransientCollection.-conj!",a);}return a}
function Xa(a){if(null!=a&&null!=a.ib)a=a.ib(a);else{var b=Xa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Xa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("ITransientCollection.-persistent!",a);}return a}function Ya(a,b,c){if(null!=a&&null!=a.Va)a=a.Va(a,b,c);else{var d=Ya[t(null==a?null:a)];if(null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=Ya._,null!=d)a=d.l?d.l(a,b,c):d.call(null,a,b,c);else throw y("ITransientAssociative.-assoc!",a);}return a}
function Za(a){if(null!=a&&null!=a.rb)a=a.rb(a);else{var b=Za[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=Za._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IChunk.-drop-first",a);}return a}function $a(a){if(null!=a&&null!=a.mb)a=a.mb(a);else{var b=$a[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=$a._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IChunkedSeq.-chunked-first",a);}return a}
function ab(a){if(null!=a&&null!=a.gb)a=a.gb(a);else{var b=ab[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=ab._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IChunkedSeq.-chunked-rest",a);}return a}function bb(){}function cb(a){if(null!=a&&null!=a.ta)a=a.ta(a);else{var b=cb[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=cb._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw y("IIterable.-iterator",a);}return a}
function db(a){this.Mb=a;this.j=1073741824;this.A=0}db.prototype.vb=function(a,b){return this.Mb.append(b)};function eb(a){var b=new ea;a.K(null,new db(b),new fb(null,5,[gb,!0,hb,!0,ib,!1,jb,!1,kb,null],null));return A.g(b)}var lb="undefined"!==typeof Math&&"undefined"!==typeof Math.imul?function(a,b){return Math.imul(a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function mb(a){a=lb(a|0,-862048943);return lb(a<<15|a>>>-15,461845907)}
function nb(a,b){a=(a|0)^(b|0);return lb(a<<13|a>>>-13,5)+-430675100|0}function ob(a,b){a=(a|0)^b;a=lb(a^a>>>16,-2048144789);a=lb(a^a>>>13,-1028477387);return a^a>>>16}function pb(a){a:{var b=1;for(var c=0;;)if(b<a.length)c=nb(c,mb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16)),b+=2;else{b=c;break a}}return ob(1===(a.length&1)?b^mb(a.charCodeAt(a.length-1)):b,lb(2,a.length))}var qb={},rb=0;
function sb(a){255<rb&&(qb={},rb=0);if(null==a)return 0;var b=qb[a];if("number"===typeof b)a=b;else{a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)d=lb(31,d)+a.charCodeAt(c),c+=1;else{b=d;break a}else b=0;else b=0;qb[a]=b;rb+=1;a=b}return a}
function tb(a){if(null!=a&&(a.j&4194304||v===a.Qb))return a.N(null)^0;if("number"===typeof a){if(isFinite(a)){if(Number.isSafeInteger(a))a=Math.floor(a)%2147483647;else{var b=new Float64Array(1);b[0]=a;b=b.buffer;a=(new DataView(b,0,4)).getInt32();b=(new DataView(b,4,4)).getInt32();a^=b}return a}switch(a){case Infinity:return 2146435072;case -Infinity:return-1048576;default:return 2146959360}}else return!0===a?a=1231:!1===a?a=1237:"string"===typeof a?(a=sb(a),a=0===a?a:ob(nb(0,mb(a)),4)):a=a instanceof
Date?a.valueOf()^0:null==a?0:Na(a)^0,a}function ub(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function vb(a,b,c,d,e){this.fb=a;this.name=b;this.Aa=c;this.Ta=d;this.ra=e;this.j=2154168321;this.A=4096}f=vb.prototype;f.toString=function(){return this.Aa};f.J=function(a,b){return b instanceof vb?this.Aa===b.Aa:!1};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return wb?wb(a,this):xb.call(null,a,this)};f.h=function(a,b){return yb?yb(a,this,b):xb.call(null,a,this,b)};f.O=function(){return this.ra};f.P=function(a,b){return new vb(this.fb,this.name,this.Aa,this.Ta,b)};
f.N=function(){var a=this.Ta;return null!=a?a:this.Ta=a=ub(pb(this.name),sb(this.fb))};f.K=function(a,b){return H(b,this.Aa)};var zb=function zb(a){switch(arguments.length){case 1:return zb.g(arguments[0]);case 2:return zb.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}};
zb.g=function(a){for(;;){if(a instanceof vb)return a;if("string"===typeof a){var b=a.indexOf("/");return 1>b?zb.h(null,a):zb.h(a.substring(0,b),a.substring(b+1,a.length))}if(a instanceof I)a=a.va;else throw Error("no conversion to symbol");}};zb.h=function(a,b){var c=null!=a?[A.g(a),"/",A.g(b)].join(""):b;return new vb(a,b,c,null,null)};zb.ga=2;function Ab(a){return null!=a?a.A&131072||v===a.Rb?!0:a.A?!1:x(bb,a):x(bb,a)}
function K(a){if(null==a)return null;if(null!=a&&(a.j&8388608||v===a.Jb))return a.I(null);if(ha(a)||"string"===typeof a)return 0===a.length?null:new M(a,0,null);if(null!=a&&null!=a[ja])return a=(null!==a&&ja in a?a[ja]:void 0).call(a),Bb.g?Bb.g(a):Bb.call(null,a);if(x(Oa,a))return Pa(a);throw Error([A.g(a)," is not ISeqable"].join(""));}function N(a){if(null==a)return null;if(null!=a&&(a.j&64||v===a.Za))return a.aa(null);a=K(a);return null==a?null:E(a)}
function Cb(a){return null!=a?null!=a&&(a.j&64||v===a.Za)?a.fa(null):(a=K(a))?a.fa(null):O:O}function P(a){return null==a?null:null!=a&&(a.j&128||v===a.Ya)?a.X():K(Cb(a))}var Q=function Q(a){switch(arguments.length){case 1:return Q.g(arguments[0]);case 2:return Q.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Q.S(arguments[0],arguments[1],2<c.length?new M(c.slice(2),0,null):null)}};Q.g=function(){return!0};
Q.h=function(a,b){return null==a?null==b:a===b||Ma(a,b)};Q.S=function(a,b,c){for(;;)if(Q.h(a,b))if(P(c))a=b,b=N(c),c=P(c);else return Q.h(b,N(c));else return!1};Q.ba=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.S(b,a,c)};Q.ga=2;function Db(a){this.C=a}Db.prototype.next=function(){if(null!=this.C){var a=N(this.C);this.C=P(this.C);return{value:a,done:!1}}return{value:null,done:!0}};function S(a){return new Db(K(a))}
function Eb(a,b){this.value=a;this.wb=b;this.jb=null;this.j=8388672;this.A=0}Eb.prototype.I=function(){return this};Eb.prototype.aa=function(){return this.value};Eb.prototype.fa=function(){null==this.jb&&(this.jb=Bb.g?Bb.g(this.wb):Bb.call(null,this.wb));return this.jb};function Bb(a){var b=a.next();return w(b.done)?null:new Eb(b.value,a)}function Fb(a){var b=0,c=1;for(a=K(a);;)if(null!=a)b+=1,c=lb(31,c)+tb(N(a))|0,a=P(a);else return ob(nb(0,mb(c)),b)}var Gb=ob(nb(0,mb(1)),0);
function Hb(a){var b=0,c=0;for(a=K(a);;)if(null!=a)b+=1,c=c+tb(N(a))|0,a=P(a);else return ob(nb(0,mb(c)),b)}var Ib=ob(nb(0,mb(0)),0);ka["null"]=!0;la["null"]=function(){return 0};Date.prototype.J=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};Ma.number=function(a,b){return a===b};Ea["function"]=!0;Fa["function"]=function(){return null};Na._=function(a){return Object.prototype.hasOwnProperty.call(a,aa)&&a[aa]||(a[aa]=++ba)};function Jb(){this.G=!1;this.j=32768;this.A=0}
Jb.prototype.Ab=function(){return this.G};function Kb(a){return a instanceof Jb}function Lb(a){return Da(a)}function Mb(a,b){var c=a.length;if(0===a.length)return b.F?b.F():b.call(null);for(var d=a[0],e=1;;)if(e<c){var g=a[e];d=b.h?b.h(d,g):b.call(null,d,g);if(Kb(d))return Da(d);e+=1}else return d}function Nb(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c];e=b.h?b.h(e,g):b.call(null,e,g);if(Kb(e))return Da(e);c+=1}else return e}
function Ob(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.h?b.h(c,g):b.call(null,c,g);if(Kb(c))return Da(c);d+=1}else return c}function Pb(a){return null!=a?a.j&2||v===a.zb?!0:a.j?!1:x(ka,a):x(ka,a)}function Qb(a){return null!=a?a.j&16||v===a.tb?!0:a.j?!1:x(pa,a):x(pa,a)}function T(a,b,c){var d=U.g?U.g(a):U.call(null,a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if(Q.h(Rb?Rb(a,c):Sb.call(null,a,c),b))return c;c+=1}else return-1}
function V(a,b,c){var d=U.g?U.g(a):U.call(null,a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if(Q.h(Rb?Rb(a,c):Sb.call(null,a,c),b))return c;--c}else return-1}function Tb(a,b){this.i=a;this.o=b}Tb.prototype.ia=function(){return this.o<this.i.length};Tb.prototype.next=function(){var a=this.i[this.o];this.o+=1;return a};function M(a,b,c){this.i=a;this.o=b;this.u=c;this.j=166592766;this.A=401408}f=M.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U.g?U.g(this):U.call(null,this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.W=function(a,b){a=b+this.o;if(0<=a&&a<this.i.length)return this.i[a];throw Error("Index out of bounds");};f.la=function(a,b,c){a=b+this.o;return 0<=a&&a<this.i.length?this.i[a]:c};
f.ta=function(){return new Tb(this.i,this.o)};f.O=function(){return this.u};f.X=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):null};f.U=function(){var a=this.i.length-this.o;return 0>a?0:a};f.N=function(){return Fb(this)};f.J=function(a,b){return Ub.h?Ub.h(this,b):Ub.call(null,this,b)};f.V=function(){return O};f.Z=function(a,b){return Ob(this.i,b,this.i[this.o],this.o+1)};f.$=function(a,b,c){return Ob(this.i,b,c,this.o)};f.aa=function(){return this.i[this.o]};
f.fa=function(){return this.o+1<this.i.length?new M(this.i,this.o+1,null):O};f.I=function(){return this.o<this.i.length?this:null};f.P=function(a,b){return b===this.u?this:new M(this.i,this.o,b)};f.T=function(a,b){return W.h?W.h(b,this):W.call(null,b,this)};M.prototype[ja]=function(){return S(this)};function Vb(a){return 0<a.length?new M(a,0,null):null}Ma._=function(a,b){return a===b};
var Wb=function Wb(a){switch(arguments.length){case 0:return Wb.F();case 1:return Wb.g(arguments[0]);case 2:return Wb.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Wb.S(arguments[0],arguments[1],2<c.length?new M(c.slice(2),0,null):null)}};Wb.F=function(){return Xb};Wb.g=function(a){return a};Wb.h=function(a,b){return null!=a?oa(a,b):new Yb(null,b,null,1,null)};
Wb.S=function(a,b,c){for(;;)if(w(c))a=Wb.h(a,b),b=N(c),c=P(c);else return Wb.h(a,b)};Wb.ba=function(a){var b=N(a),c=P(a);a=N(c);c=P(c);return this.S(b,a,c)};Wb.ga=2;function U(a){if(null!=a)if(null!=a&&(a.j&2||v===a.zb))a=a.U(null);else if(ha(a))a=a.length;else if("string"===typeof a)a=a.length;else if(null!=a&&(a.j&8388608||v===a.Jb))a:{a=K(a);for(var b=0;;){if(Pb(a)){a=b+la(a);break a}a=P(a);b+=1}}else a=la(a);else a=0;return a}
function Zb(a,b,c){for(;;){if(null==a)return c;if(0===b)return K(a)?N(a):c;if(Qb(a))return D(a,b,c);if(K(a))a=P(a),--b;else return c}}function Sb(a){switch(arguments.length){case 2:return Rb(arguments[0],arguments[1]);case 3:return $b(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}
function Rb(a,b){if("number"!==typeof b)throw Error("Index argument to nth must be a number");if(null==a)return a;if(null!=a&&(a.j&16||v===a.tb))return a.W(null,b);if(ha(a)){if(-1<b&&b<a.length)return a[b|0];throw Error("Index out of bounds");}if("string"===typeof a){if(-1<b&&b<a.length)return a.charAt(b|0);throw Error("Index out of bounds");}if(null!=a&&(a.j&64||v===a.Za)||null!=a&&(a.j&16777216||v===a.ub)){if(0>b)throw Error("Index out of bounds");a:for(;;){if(null==a)throw Error("Index out of bounds");
if(0===b){if(K(a)){a=N(a);break a}throw Error("Index out of bounds");}if(Qb(a)){a=D(a,b);break a}if(K(a))a=P(a),--b;else throw Error("Index out of bounds");}return a}if(x(pa,a))return D(a,b);throw Error(["nth not supported on this type ",A.g(ia(null==a?null:a.constructor))].join(""));}
function $b(a,b,c){if("number"!==typeof b)throw Error("Index argument to nth must be a number.");if(null==a)return c;if(null!=a&&(a.j&16||v===a.tb))return a.la(null,b,c);if(ha(a))return-1<b&&b<a.length?a[b|0]:c;if("string"===typeof a)return-1<b&&b<a.length?a.charAt(b|0):c;if(null!=a&&(a.j&64||v===a.Za)||null!=a&&(a.j&16777216||v===a.ub))return 0>b?c:Zb(a,b,c);if(x(pa,a))return D(a,b,c);throw Error(["nth not supported on this type ",A.g(ia(null==a?null:a.constructor))].join(""));}
function xb(a){switch(arguments.length){case 2:return wb(arguments[0],arguments[1]);case 3:return yb(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}function wb(a,b){return null==a?null:null!=a&&(a.j&256||v===a.Db)?a.ka(null,b):ha(a)?null!=b&&b<a.length?a[b|0]:null:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):null:x(sa,a)?ta(a,b):null}
function yb(a,b,c){return null!=a?null!=a&&(a.j&256||v===a.Db)?a.H(null,b,c):ha(a)?null!=b&&-1<b&&b<a.length?a[b|0]:c:"string"===typeof a?null!=b&&-1<b&&b<a.length?a.charAt(b|0):c:x(sa,a)?ta(a,b,c):c:c}var ac=function ac(a){switch(arguments.length){case 3:return ac.l(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ac.S(arguments[0],arguments[1],arguments[2],3<c.length?new M(c.slice(3),0,null):null)}};
ac.l=function(a,b,c){return null!=a&&(a.j&512||v===a.yb)?a.xa(null,b,c):null!=a?xa(a,b,c):bc([b,c])};ac.S=function(a,b,c,d){for(;;)if(a=ac.l(a,b,c),w(d))b=N(d),c=N(P(d)),d=P(P(d));else return a};ac.ba=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);d=P(d);return this.S(b,a,c,d)};ac.ga=3;function cc(a,b){this.s=a;this.u=b;this.j=393217;this.A=0}f=cc.prototype;f.O=function(){return this.u};f.P=function(a,b){return new cc(this.s,b)};
f.call=function(a){switch(arguments.length-1){case 0:return this.F();case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);case 3:return this.l(arguments[1],arguments[2],arguments[3]);case 4:return this.ea(arguments[1],arguments[2],arguments[3],arguments[4]);case 5:return this.ua(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 6:return this.Na(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);case 7:return this.Oa(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7]);case 8:return this.Pa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8]);case 9:return this.Qa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9]);case 10:return this.Ca(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10]);
case 11:return this.Da(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11]);case 12:return this.Ea(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12]);case 13:return this.Fa(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],
arguments[11],arguments[12],arguments[13]);case 14:return this.Ga(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14]);case 15:return this.Ha(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15]);case 16:return this.Ia(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16]);case 17:return this.Ja(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17]);case 18:return this.Ka(arguments[1],arguments[2],
arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18]);case 19:return this.La(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19]);case 20:return this.Ma(arguments[1],
arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],arguments[18],arguments[19],arguments[20]);case 21:return this.nb(arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6],arguments[7],arguments[8],arguments[9],arguments[10],arguments[11],arguments[12],arguments[13],arguments[14],arguments[15],arguments[16],arguments[17],
arguments[18],arguments[19],arguments[20],arguments[21]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.F=function(){return this.s.F?this.s.F():this.s.call(null)};f.g=function(a){return this.s.g?this.s.g(a):this.s.call(null,a)};f.h=function(a,b){return this.s.h?this.s.h(a,b):this.s.call(null,a,b)};f.l=function(a,b,c){return this.s.l?this.s.l(a,b,c):this.s.call(null,a,b,c)};
f.ea=function(a,b,c,d){return this.s.ea?this.s.ea(a,b,c,d):this.s.call(null,a,b,c,d)};f.ua=function(a,b,c,d,e){return this.s.ua?this.s.ua(a,b,c,d,e):this.s.call(null,a,b,c,d,e)};f.Na=function(a,b,c,d,e,g){return this.s.Na?this.s.Na(a,b,c,d,e,g):this.s.call(null,a,b,c,d,e,g)};f.Oa=function(a,b,c,d,e,g,h){return this.s.Oa?this.s.Oa(a,b,c,d,e,g,h):this.s.call(null,a,b,c,d,e,g,h)};f.Pa=function(a,b,c,d,e,g,h,k){return this.s.Pa?this.s.Pa(a,b,c,d,e,g,h,k):this.s.call(null,a,b,c,d,e,g,h,k)};
f.Qa=function(a,b,c,d,e,g,h,k,m){return this.s.Qa?this.s.Qa(a,b,c,d,e,g,h,k,m):this.s.call(null,a,b,c,d,e,g,h,k,m)};f.Ca=function(a,b,c,d,e,g,h,k,m,l){return this.s.Ca?this.s.Ca(a,b,c,d,e,g,h,k,m,l):this.s.call(null,a,b,c,d,e,g,h,k,m,l)};f.Da=function(a,b,c,d,e,g,h,k,m,l,n){return this.s.Da?this.s.Da(a,b,c,d,e,g,h,k,m,l,n):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n)};f.Ea=function(a,b,c,d,e,g,h,k,m,l,n,p){return this.s.Ea?this.s.Ea(a,b,c,d,e,g,h,k,m,l,n,p):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p)};
f.Fa=function(a,b,c,d,e,g,h,k,m,l,n,p,q){return this.s.Fa?this.s.Fa(a,b,c,d,e,g,h,k,m,l,n,p,q):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q)};f.Ga=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r){return this.s.Ga?this.s.Ga(a,b,c,d,e,g,h,k,m,l,n,p,q,r):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r)};f.Ha=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u){return this.s.Ha?this.s.Ha(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u)};
f.Ia=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z){return this.s.Ia?this.s.Ia(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z)};f.Ja=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B){return this.s.Ja?this.s.Ja(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B)};f.Ka=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F){return this.s.Ka?this.s.Ka(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F)};
f.La=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J){return this.s.La?this.s.La(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J)};f.Ma=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R){return this.s.Ma?this.s.Ma(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R):this.s.call(null,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R)};
f.nb=function(a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R,ca){return dc.nb?dc.nb(this.s,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,new M([R,ca],0,null)):dc.call(null,this.s,a,b,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R,ca)};function ec(a,b){return"function"===typeof a?new cc(a,b):null==a?null:Ga(a,b)}function fc(a){var b=null!=a;return(b?null!=a?a.j&131072||v===a.Gb||(a.j?0:x(Ea,a)):x(Ea,a):b)?Fa(a):null}function gc(a){return null!=a?a.j&16777216||v===a.ub?!0:a.j?!1:x(Qa,a):x(Qa,a)}
function hc(a){return null==a?!1:null!=a?a.j&1024||v===a.Tb?!0:a.j?!1:x(za,a):x(za,a)}function ic(a){return null!=a?a.j&67108864||v===a.Vb?!0:a.j?!1:x(Sa,a):x(Sa,a)}function jc(a){return null!=a?a.j&16384||v===a.Wb?!0:a.j?!1:x(Ca,a):x(Ca,a)}function kc(a){return null!=a?a.A&512||v===a.Ob?!0:!1:!1}function lc(a,b,c,d,e){for(;;){if(0===e)return c;c[d]=a[b];d+=1;--e;b+=1}}var mc={};function nc(a){return null==a?!1:!1===a?!1:!0}
function oc(a,b){return null!=a&&(a.j&512||v===a.yb)?a.Ua(null,b):x(va,a)?wa(a,b):yb(a,b,mc)===mc?!1:!0}function pc(a,b){var c=K(b);return c?(b=N(c),c=P(c),qc?qc(a,b,c):rc.call(null,a,b,c)):a.F?a.F():a.call(null)}function sc(a,b,c){for(c=K(c);;)if(c){var d=N(c);b=a.h?a.h(b,d):a.call(null,b,d);if(Kb(b))return Da(b);c=P(c)}else return b}
function tc(a,b){a=cb(a);if(w(a.ia()))for(var c=a.next();;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Kb(c))return Da(c)}else return c;else return b.F?b.F():b.call(null)}function uc(a,b,c){for(a=cb(a);;)if(a.ia()){var d=a.next();c=b.h?b.h(c,d):b.call(null,c,d);if(Kb(c))return Da(c)}else return c}
function rc(a){switch(arguments.length){case 2:var b=arguments[0],c=arguments[1];return null!=c&&(c.j&524288||v===c.Ib)?c.Z(null,b):ha(c)?Mb(c,b):"string"===typeof c?Mb(c,b):x(Ha,c)?Ia(c,b):Ab(c)?tc(c,b):pc(b,c);case 3:return qc(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}
function qc(a,b,c){return null!=c&&(c.j&524288||v===c.Ib)?c.$(null,a,b):ha(c)?Nb(c,a,b):"string"===typeof c?Nb(c,a,b):x(Ha,c)?Ia(c,a,b):Ab(c)?uc(c,a,b):sc(a,b,c)}function vc(a,b){return(null!=b?b.j&1048576||v===b.Cb||(b.j?0:x(Ka,b)):x(Ka,b))?La(b,a):qc(function(c,d){var e=Aa(d);d=Ba(d);return a.l?a.l(c,e,d):a.call(null,c,e,d)},!0,b)}function wc(a){return a}function xc(a){a=(a-a%2)/2;return 0<=a?Math.floor(a):Math.ceil(a)}
function yc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}var A=function A(a){switch(arguments.length){case 0:return A.F();case 1:return A.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return A.S(arguments[0],1<c.length?new M(c.slice(1),0,null):null)}};A.F=function(){return""};A.g=function(a){return null==a?"":[a].join("")};
A.S=function(a,b){for(a=new ea(A.g(a));;)if(w(b))a=a.append(A.g(N(b))),b=P(b);else return a.toString()};A.ba=function(a){var b=N(a);a=P(a);return this.S(b,a)};A.ga=1;function Ub(a,b){if(gc(b))if(Pb(a)&&Pb(b)&&U(a)!==U(b))a=!1;else a:for(a=K(a),b=K(b);;){if(null==a){a=null==b;break a}if(null!=b&&Q.h(N(a),N(b)))a=P(a),b=P(b);else{a=!1;break a}}else a=null;return nc(a)}function Yb(a,b,c,d,e){this.u=a;this.first=b;this.wa=c;this.count=d;this.v=e;this.j=65937646;this.A=8192}f=Yb.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,this.count)}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return 1===this.count?null:this.wa};f.U=function(){return this.count};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};
f.V=function(){return Ga(O,this.u)};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return 1===this.count?O:this.wa};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new Yb(b,this.first,this.wa,this.count,this.v)};f.T=function(a,b){return new Yb(this.u,b,this,this.count+1,null)};Yb.prototype[ja]=function(){return S(this)};function zc(a){this.u=a;this.j=65937614;this.A=8192}f=zc.prototype;
f.toString=function(){return eb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return null};f.U=function(){return 0};f.N=function(){return Gb};f.J=function(a,b){return(null!=b?b.j&33554432||v===b.Sb||(b.j?0:x(Ra,b)):x(Ra,b))||gc(b)?null==K(b):!1};f.V=function(){return this};
f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return null};f.fa=function(){return O};f.I=function(){return null};f.P=function(a,b){return b===this.u?this:new zc(b)};f.T=function(a,b){return new Yb(this.u,b,null,1,null)};var O=new zc(null);zc.prototype[ja]=function(){return S(this)};function Ac(a,b,c,d){this.u=a;this.first=b;this.wa=c;this.v=d;this.j=65929452;this.A=8192}f=Ac.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return null==this.wa?null:K(this.wa)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};
f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return this.first};f.fa=function(){return null==this.wa?O:this.wa};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new Ac(b,this.first,this.wa,this.v)};f.T=function(a,b){return new Ac(null,b,this,null)};Ac.prototype[ja]=function(){return S(this)};function W(a,b){return null==b?new Yb(null,a,null,1,null):null!=b&&(b.j&64||v===b.Za)?new Ac(null,a,b,null):new Ac(null,a,K(b),null)}
function I(a,b,c,d){this.fb=a;this.name=b;this.va=c;this.Ta=d;this.j=2153775105;this.A=4096}f=I.prototype;f.toString=function(){return[":",A.g(this.va)].join("")};f.J=function(a,b){return b instanceof I?this.va===b.va:!1};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return wb(a,this)};f.h=function(a,b){return yb(a,this,b)};f.N=function(){var a=this.Ta;return null!=a?a:this.Ta=a=ub(pb(this.name),sb(this.fb))+2654435769|0};f.K=function(a,b){return H(b,[":",A.g(this.va)].join(""))};function Bc(a){if(null!=a&&(a.A&4096||v===a.Hb))return a.fb;throw Error(["Doesn't support namespace: ",A.g(a)].join(""));}
var Cc=function Cc(a){switch(arguments.length){case 1:return Cc.g(arguments[0]);case 2:return Cc.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}};Cc.g=function(a){if(a instanceof I)return a;if(a instanceof vb)return new I(Bc(a),Dc.g?Dc.g(a):Dc.call(null,a),a.Aa,null);if(Q.h("/",a))return new I(null,a,a,null);if("string"===typeof a){var b=a.split("/");return 2===b.length?new I(b[0],b[1],a,null):new I(null,b[0],a,null)}return null};
Cc.h=function(a,b){a=a instanceof I?Dc.g?Dc.g(a):Dc.call(null,a):a instanceof vb?Dc.g?Dc.g(a):Dc.call(null,a):a;b=b instanceof I?Dc.g?Dc.g(b):Dc.call(null,b):b instanceof vb?Dc.g?Dc.g(b):Dc.call(null,b):b;return new I(a,b,[w(a)?[A.g(a),"/"].join(""):null,A.g(b)].join(""),null)};Cc.ga=2;function Ec(a,b,c){this.u=a;this.ab=b;this.C=null;this.v=c;this.j=32374988;this.A=1}f=Ec.prototype;f.toString=function(){return eb(this)};
function Fc(a){null!=a.ab&&(a.C=a.ab.F?a.ab.F():a.ab.call(null),a.ab=null);return a.C}f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){this.I(null);return null==this.C?null:P(this.C)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};f.V=function(){return Ga(O,this.u)};
f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){this.I(null);return null==this.C?null:N(this.C)};f.fa=function(){this.I(null);return null!=this.C?Cb(this.C):O};f.I=function(){Fc(this);if(null==this.C)return null;for(var a=this.C;;)if(a instanceof Ec)a=Fc(a);else return this.C=a,K(this.C)};f.P=function(a,b){var c=this;return b===this.u?c:new Ec(b,function(){return c.I(null)},this.v)};f.T=function(a,b){return W(b,this)};Ec.prototype[ja]=function(){return S(this)};
function Gc(a){this.lb=a;this.end=0;this.j=2;this.A=0}Gc.prototype.add=function(a){this.lb[this.end]=a;return this.end+=1};Gc.prototype.sa=function(){var a=new Hc(this.lb,0,this.end);this.lb=null;return a};Gc.prototype.U=function(){return this.end};function Hc(a,b,c){this.i=a;this.R=b;this.end=c;this.j=524306;this.A=0}f=Hc.prototype;f.U=function(){return this.end-this.R};f.W=function(a,b){return this.i[this.R+b]};f.la=function(a,b,c){return 0<=b&&b<this.end-this.R?this.i[this.R+b]:c};
f.rb=function(){if(this.R===this.end)throw Error("-drop-first of empty chunk");return new Hc(this.i,this.R+1,this.end)};f.Z=function(a,b){return Ob(this.i,b,this.i[this.R],this.R+1)};f.$=function(a,b,c){return Ob(this.i,b,c,this.R)};function Ic(a,b,c,d){this.sa=a;this.oa=b;this.u=c;this.v=d;this.j=31850732;this.A=1536}f=Ic.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){return 1<la(this.sa)?new Ic(Za(this.sa),this.oa,null,null):null==this.oa?null:Pa(this.oa)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};
f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};f.aa=function(){return D(this.sa,0)};f.fa=function(){return 1<la(this.sa)?new Ic(Za(this.sa),this.oa,null,null):null==this.oa?O:this.oa};f.I=function(){return this};f.mb=function(){return this.sa};f.gb=function(){return null==this.oa?O:this.oa};f.P=function(a,b){return b===this.u?this:new Ic(this.sa,this.oa,b,this.v)};f.T=function(a,b){return W(b,this)};f.sb=function(){return null==this.oa?null:this.oa};Ic.prototype[ja]=function(){return S(this)};
function Jc(a,b){return 0===la(a)?b:new Ic(a,b,null,null)}function Kc(a,b){a.add(b)}function Lc(a,b){if(Pb(b))return U(b);var c=0;for(b=K(b);;)if(null!=b&&c<a)c+=1,b=P(b);else return c}var Mc=function Mc(a){if(null==a)return null;var c=P(a);return null==c?K(N(a)):W(N(a),Mc.g?Mc.g(c):Mc.call(null,c))};
function Nc(a,b,c){var d=K(c);if(0===b)return a.F?a.F():a.call(null);c=E(d);var e=G(d);if(1===b)return a.g?a.g(c):a.call(null,c);d=E(e);var g=G(e);if(2===b)return a.h?a.h(c,d):a.call(null,c,d);e=E(g);var h=G(g);if(3===b)return a.l?a.l(c,d,e):a.call(null,c,d,e);g=E(h);var k=G(h);if(4===b)return a.ea?a.ea(c,d,e,g):a.call(null,c,d,e,g);h=E(k);var m=G(k);if(5===b)return a.ua?a.ua(c,d,e,g,h):a.call(null,c,d,e,g,h);k=E(m);var l=G(m);if(6===b)return a.Na?a.Na(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);m=E(l);
var n=G(l);if(7===b)return a.Oa?a.Oa(c,d,e,g,h,k,m):a.call(null,c,d,e,g,h,k,m);l=E(n);var p=G(n);if(8===b)return a.Pa?a.Pa(c,d,e,g,h,k,m,l):a.call(null,c,d,e,g,h,k,m,l);n=E(p);var q=G(p);if(9===b)return a.Qa?a.Qa(c,d,e,g,h,k,m,l,n):a.call(null,c,d,e,g,h,k,m,l,n);p=E(q);var r=G(q);if(10===b)return a.Ca?a.Ca(c,d,e,g,h,k,m,l,n,p):a.call(null,c,d,e,g,h,k,m,l,n,p);q=E(r);var u=G(r);if(11===b)return a.Da?a.Da(c,d,e,g,h,k,m,l,n,p,q):a.call(null,c,d,e,g,h,k,m,l,n,p,q);r=E(u);var z=G(u);if(12===b)return a.Ea?
a.Ea(c,d,e,g,h,k,m,l,n,p,q,r):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r);u=E(z);var B=G(z);if(13===b)return a.Fa?a.Fa(c,d,e,g,h,k,m,l,n,p,q,r,u):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u);z=E(B);var F=G(B);if(14===b)return a.Ga?a.Ga(c,d,e,g,h,k,m,l,n,p,q,r,u,z):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z);B=E(F);var J=G(F);if(15===b)return a.Ha?a.Ha(c,d,e,g,h,k,m,l,n,p,q,r,u,z,B):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B);F=E(J);var R=G(J);if(16===b)return a.Ia?a.Ia(c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F):a.call(null,
c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F);J=E(R);var ca=G(R);if(17===b)return a.Ja?a.Ja(c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J);R=E(ca);var ya=G(ca);if(18===b)return a.Ka?a.Ka(c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R);ca=E(ya);ya=G(ya);if(19===b)return a.La?a.La(c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R,ca):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R,ca);var Ud=E(ya);G(ya);if(20===b)return a.Ma?a.Ma(c,d,e,g,h,k,m,l,n,p,q,r,
u,z,B,F,J,R,ca,Ud):a.call(null,c,d,e,g,h,k,m,l,n,p,q,r,u,z,B,F,J,R,ca,Ud);throw Error("Only up to 20 arguments supported on functions");}function Oc(a){return null!=a&&(a.j&128||v===a.Ya)?a.X():K(Cb(a))}function Pc(a,b,c){return null==c?a.g?a.g(b):a.call(a,b):Qc(a,b,E(c),Oc(c))}function Qc(a,b,c,d){return null==d?a.h?a.h(b,c):a.call(a,b,c):Rc(a,b,c,E(d),Oc(d))}function Rc(a,b,c,d,e){return null==e?a.l?a.l(b,c,d):a.call(a,b,c,d):Sc(a,b,c,d,E(e),Oc(e))}
function Sc(a,b,c,d,e,g){if(null==g)return a.ea?a.ea(b,c,d,e):a.call(a,b,c,d,e);var h=E(g),k=P(g);if(null==k)return a.ua?a.ua(b,c,d,e,h):a.call(a,b,c,d,e,h);g=E(k);var m=P(k);if(null==m)return a.Na?a.Na(b,c,d,e,h,g):a.call(a,b,c,d,e,h,g);k=E(m);var l=P(m);if(null==l)return a.Oa?a.Oa(b,c,d,e,h,g,k):a.call(a,b,c,d,e,h,g,k);m=E(l);var n=P(l);if(null==n)return a.Pa?a.Pa(b,c,d,e,h,g,k,m):a.call(a,b,c,d,e,h,g,k,m);l=E(n);var p=P(n);if(null==p)return a.Qa?a.Qa(b,c,d,e,h,g,k,m,l):a.call(a,b,c,d,e,h,g,k,m,
l);n=E(p);var q=P(p);if(null==q)return a.Ca?a.Ca(b,c,d,e,h,g,k,m,l,n):a.call(a,b,c,d,e,h,g,k,m,l,n);p=E(q);var r=P(q);if(null==r)return a.Da?a.Da(b,c,d,e,h,g,k,m,l,n,p):a.call(a,b,c,d,e,h,g,k,m,l,n,p);q=E(r);var u=P(r);if(null==u)return a.Ea?a.Ea(b,c,d,e,h,g,k,m,l,n,p,q):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q);r=E(u);var z=P(u);if(null==z)return a.Fa?a.Fa(b,c,d,e,h,g,k,m,l,n,p,q,r):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r);u=E(z);var B=P(z);if(null==B)return a.Ga?a.Ga(b,c,d,e,h,g,k,m,l,n,p,q,r,u):a.call(a,b,
c,d,e,h,g,k,m,l,n,p,q,r,u);z=E(B);var F=P(B);if(null==F)return a.Ha?a.Ha(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r,u,z);B=E(F);var J=P(F);if(null==J)return a.Ia?a.Ia(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B);F=E(J);var R=P(J);if(null==R)return a.Ja?a.Ja(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F);J=E(R);var ca=P(R);if(null==ca)return a.Ka?a.Ka(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J):a.call(a,b,c,d,e,h,g,k,m,l,
n,p,q,r,u,z,B,F,J);R=E(ca);var ya=P(ca);if(null==ya)return a.La?a.La(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J,R):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J,R);ca=E(ya);ya=P(ya);if(null==ya)return a.Ma?a.Ma(b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J,R,ca):a.call(a,b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J,R,ca);b=[b,c,d,e,h,g,k,m,l,n,p,q,r,u,z,B,F,J,R,ca];for(c=ya;;)if(c)b.push(E(c)),c=P(c);else break;return a.apply(a,b)}
function dc(a){switch(arguments.length){case 2:return Tc(arguments[0],arguments[1]);case 3:return Uc(arguments[0],arguments[1],arguments[2]);case 4:var b=arguments[0];var c=arguments[1],d=arguments[2],e=arguments[3];b.ba?(c=W(c,W(d,e)),d=b.ga,e=2+Lc(d-1,e),b=e<=d?Nc(b,e,c):b.ba(c)):b=Qc(b,c,d,K(e));return b;case 5:b=arguments[0];c=arguments[1];d=arguments[2];var g=arguments[3];e=arguments[4];b.ba?(c=W(c,W(d,W(g,e))),d=b.ga,e=3+Lc(d-2,e),b=e<=d?Nc(b,e,c):b.ba(c)):b=Rc(b,c,d,g,K(e));return b;default:e=
[];b=arguments.length;for(c=0;;)if(c<b)e.push(arguments[c]),c+=1;else break;b=arguments[0];c=arguments[1];d=arguments[2];g=arguments[3];var h=arguments[4];e=5<e.length?new M(e.slice(5),0,null):null;b.ba?(e=Mc(e),c=W(c,W(d,W(g,W(h,e)))),d=b.ga,e=4+Lc(d-3,e),b=e<=d?Nc(b,e,c):b.ba(c)):b=Sc(b,c,d,g,h,Mc(e));return b}}function Tc(a,b){if(a.ba){var c=a.ga,d=Lc(c+1,b);return d<=c?Nc(a,d,b):a.ba(b)}b=K(b);return null==b?a.F?a.F():a.call(a):Pc(a,E(b),Oc(b))}
function Uc(a,b,c){if(a.ba){b=W(b,c);var d=a.ga;c=Lc(d,c)+1;return c<=d?Nc(a,c,b):a.ba(b)}return Pc(a,b,K(c))}function Vc(a){if(null!=a&&(a.j&64||v===a.Za))if(P(a)){a:{var b=[];for(a=K(a);;)if(null!=a)b.push(N(a)),a=P(a);else break a}b=bc(b)}else b=K(a)?N(a):Wc;else b=a;return b}function Xc(a){this.Lb=a;this.j=393216;this.A=0}f=Xc.prototype;f.P=function(a,b){return new Xc(b)};f.O=function(){return this.Lb};f.ia=function(){return!1};f.next=function(){return Error("No such element")};f.remove=function(){return Error("Unsupported operation")};
function Yc(a,b){for(;;){if(null==K(b))return!0;var c=N(b);c=a.g?a.g(c):a.call(null,c);if(w(c))b=P(b);else return!1}}function Zc(a,b){return new Ec(null,function(){var c=K(b);if(c){if(kc(c)){for(var d=$a(c),e=U(d),g=new Gc(Array(e)),h=0;;)if(h<e){var k=function(){var m=D(d,h);return a.g?a.g(m):a.call(null,m)}();null!=k&&g.add(k);h+=1}else break;return Jc(g.sa(),Zc(a,ab(c)))}e=function(){var m=N(c);return a.g?a.g(m):a.call(null,m)}();return null==e?Zc(a,Cb(c)):W(e,Zc(a,Cb(c)))}return null},null)}
var X=function X(a){switch(arguments.length){case 1:return X.g(arguments[0]);case 2:return X.h(arguments[0],arguments[1]);case 3:return X.l(arguments[0],arguments[1],arguments[2]);case 4:return X.ea(arguments[0],arguments[1],arguments[2],arguments[3]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return X.S(arguments[0],arguments[1],arguments[2],arguments[3],4<c.length?new M(c.slice(4),0,null):null)}};
X.g=function(a){return function(b){return function(){function c(k,m){m=a.g?a.g(m):a.call(null,m);return b.h?b.h(k,m):b.call(null,k,m)}function d(k){return b.g?b.g(k):b.call(null,k)}function e(){return b.F?b.F():b.call(null)}var g=null,h=function(){function k(l,n,p){var q=null;if(2<arguments.length){q=0;for(var r=Array(arguments.length-2);q<r.length;)r[q]=arguments[q+2],++q;q=new M(r,0,null)}return m.call(this,l,n,q)}function m(l,n,p){n=Uc(a,n,p);return b.h?b.h(l,n):b.call(null,l,n)}k.ga=2;k.ba=function(l){var n=
N(l);l=P(l);var p=N(l);l=Cb(l);return m(n,p,l)};k.S=m;return k}();g=function(k,m,l){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,k);case 2:return c.call(this,k,m);default:var n=null;if(2<arguments.length){n=0;for(var p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0,null)}return h.S(k,m,n)}throw Error("Invalid arity: "+arguments.length);};g.ga=2;g.ba=h.ba;g.F=e;g.g=d;g.h=c;g.S=h.S;return g}()}};
X.h=function(a,b){return new Ec(null,function(){var c=K(b);if(c){if(kc(c)){for(var d=$a(c),e=U(d),g=new Gc(Array(e)),h=0;;)if(h<e)Kc(g,function(){var k=D(d,h);return a.g?a.g(k):a.call(null,k)}()),h+=1;else break;return Jc(g.sa(),X.h(a,ab(c)))}return W(function(){var k=N(c);return a.g?a.g(k):a.call(null,k)}(),X.h(a,Cb(c)))}return null},null)};
X.l=function(a,b,c){return new Ec(null,function(){var d=K(b),e=K(c);if(d&&e){var g=N(d);var h=N(e);g=a.h?a.h(g,h):a.call(null,g,h);d=W(g,X.l(a,Cb(d),Cb(e)))}else d=null;return d},null)};X.ea=function(a,b,c,d){return new Ec(null,function(){var e=K(b),g=K(c),h=K(d);if(e&&g&&h){var k=N(e);var m=N(g),l=N(h);k=a.l?a.l(k,m,l):a.call(null,k,m,l);e=W(k,X.ea(a,Cb(e),Cb(g),Cb(h)))}else e=null;return e},null)};
X.S=function(a,b,c,d,e){return X.h(function(g){return Tc(a,g)},function k(h){return new Ec(null,function(){var m=X.h(K,h);return Yc(wc,m)?W(X.h(N,m),k(X.h(Cb,m))):null},null)}(Wb.S(e,d,Vb([c,b]))))};X.ba=function(a){var b=N(a),c=P(a);a=N(c);var d=P(c);c=N(d);var e=P(d);d=N(e);e=P(e);return this.S(b,a,c,d,e)};X.ga=4;function $c(a,b){return null!=a?null!=a&&(a.A&4||v===a.Pb)?Ga(Xa(qc(Wa,Va(a),b)),fc(a)):qc(oa,a,b):qc(Wb,a,b)}function ad(a,b){this.D=a;this.i=b}
function bd(a){return new ad(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function cd(a){a=a.m;return 32>a?0:a-1>>>5<<5}function dd(a,b,c){for(;;){if(0===b)return c;var d=bd(a);d.i[0]=c;c=d;b-=5}}var ed=function ed(a,b,c,d){var g=new ad(c.D,C(c.i)),h=a.m-1>>>b&31;5===b?g.i[h]=d:(c=c.i[h],null!=c?(b-=5,a=ed.ea?ed.ea(a,b,c,d):ed.call(null,a,b,c,d)):a=dd(null,b-5,d),g.i[h]=a);return g};
function fd(a,b){if(b>=cd(a))return a.da;var c=a.root;for(a=a.shift;;)if(0<a){var d=a-5;c=c.i[b>>>a&31];a=d}else return c.i}function gd(a,b){if(0<=b&&b<a.m)b=fd(a,b);else throw a=a.m,Error(["No item ",A.g(b)," in vector of length ",A.g(a)].join(""));return b}var hd=function hd(a,b,c,d,e){var h=new ad(c.D,C(c.i));if(0===b)h.i[d&31]=e;else{var k=d>>>b&31;b-=5;c=c.i[k];a=hd.ua?hd.ua(a,b,c,d,e):hd.call(null,a,b,c,d,e);h.i[k]=a}return h};
function id(a,b,c){this.kb=this.o=0;this.i=a;this.Nb=b;this.start=0;this.end=c}id.prototype.ia=function(){return this.o<this.end};id.prototype.next=function(){32===this.o-this.kb&&(this.i=fd(this.Nb,this.o),this.kb+=32);var a=this.i[this.o&31];this.o+=1;return a};function jd(a,b,c,d){return c<d?kd(a,b,Rb(a,c),c+1,d):b.F?b.F():b.call(null)}
function kd(a,b,c,d,e){var g=c;c=d;for(d=fd(a,d);;)if(c<e){var h=c&31;d=0===h?fd(a,c):d;h=d[h];g=b.h?b.h(g,h):b.call(null,g,h);if(Kb(g))return Da(g);c+=1}else return g}function Y(a,b,c,d,e,g){this.u=a;this.m=b;this.shift=c;this.root=d;this.da=e;this.v=g;this.j=167666463;this.A=401412}f=Y.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){return"number"===typeof b?this.la(null,b,c):c};
f.hb=function(a,b,c){a=0;for(var d=c;;)if(a<this.m){var e=fd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=g+a,k=e[g];d=b.l?b.l(d,h,k):b.call(null,d,h,k);if(Kb(d)){e=d;break a}g+=1}else{e=d;break a}if(Kb(e))return Da(e);a+=c;d=e}else return d};f.W=function(a,b){return gd(this,b)[b&31]};f.la=function(a,b,c){return 0<=b&&b<this.m?fd(this,b)[b&31]:c};
f.ob=function(a,b){if(0<=a&&a<this.m){if(cd(this)<=a){var c=C(this.da);c[a&31]=b;return new Y(this.u,this.m,this.shift,this.root,c,null)}return new Y(this.u,this.m,this.shift,hd(this,this.shift,this.root,a,b),this.da,null)}if(a===this.m)return this.T(null,b);throw Error(["Index ",A.g(a)," out of bounds  [0,",A.g(this.m),"]"].join(""));};f.ta=function(){var a=this.m;return new id(0<U(this)?fd(this,0):null,this,a)};f.O=function(){return this.u};f.U=function(){return this.m};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){if(b instanceof Y)if(this.m===U(b))for(a=this.ta(null),b=b.ta(null);;)if(a.ia()){var c=a.next(),d=b.next();if(!Q.h(c,d))return!1}else return!0;else return!1;else return Ub(this,b)};f.Xa=function(){return new ld(this.m,this.shift,md.g?md.g(this.root):md.call(null,this.root),nd.g?nd.g(this.da):nd.call(null,this.da))};f.V=function(){return Ga(Xb,this.u)};f.Z=function(a,b){return jd(this,b,0,this.m)};
f.$=function(a,b,c){a=0;for(var d=c;;)if(a<this.m){var e=fd(this,a);c=e.length;a:for(var g=0;;)if(g<c){var h=e[g];d=b.h?b.h(d,h):b.call(null,d,h);if(Kb(d)){e=d;break a}g+=1}else{e=d;break a}if(Kb(e))return Da(e);a+=c;d=e}else return d};f.xa=function(a,b,c){if("number"===typeof b)return this.ob(b,c);throw Error("Vector's key for assoc must be a number.");};f.Ua=function(a,b){return"number"!==typeof b||isNaN(b)||Infinity===b||parseFloat(b)!==parseInt(b,10)?!1:0<=b&&b<this.m};
f.I=function(){if(0===this.m)return null;if(32>=this.m)return new M(this.da,0,null);a:{var a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.i[0];else{a=a.i;break a}}return od?od(this,a,0,0):pd.call(null,this,a,0,0)};f.P=function(a,b){return b===this.u?this:new Y(b,this.m,this.shift,this.root,this.da,this.v)};
f.T=function(a,b){if(32>this.m-cd(this)){a=this.da.length;for(var c=Array(a+1),d=0;;)if(d<a)c[d]=this.da[d],d+=1;else break;c[a]=b;return new Y(this.u,this.m+1,this.shift,this.root,c,null)}a=(c=this.m>>>5>1<<this.shift)?this.shift+5:this.shift;c?(c=bd(null),c.i[0]=this.root,d=dd(null,this.shift,new ad(null,this.da)),c.i[1]=d):c=ed(this,this.shift,this.root,new ad(null,this.da));return new Y(this.u,this.m+1,a,c,[b],null)};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){if("number"===typeof a)return this.W(null,a);throw Error("Key must be integer");};
var qd=new ad(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),Xb=new Y(null,0,5,qd,[],Gb);Y.prototype[ja]=function(){return S(this)};function rd(a,b,c,d,e){this.ja=a;this.node=b;this.o=c;this.R=d;this.u=e;this.v=null;this.j=32375020;this.A=263680}f=rd.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){if(this.R+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.R+1;a=od?od(a,b,c,d):pd.call(null,a,b,c,d);return null==a?null:a}return this.sb()};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};f.Z=function(a,b){return jd(this.ja,b,this.o+this.R,U(this.ja))};f.$=function(a,b,c){return kd(this.ja,b,c,this.o+this.R,U(this.ja))};f.aa=function(){return this.node[this.R]};f.fa=function(){if(this.R+1<this.node.length){var a=this.ja;var b=this.node,c=this.o,d=this.R+1;a=od?od(a,b,c,d):pd.call(null,a,b,c,d);return null==a?O:a}return this.gb(null)};f.I=function(){return this};
f.mb=function(){var a=this.node;return new Hc(a,this.R,a.length)};f.gb=function(){var a=this.o+this.node.length;if(a<la(this.ja)){var b=this.ja,c=fd(this.ja,a);return od?od(b,c,a,0):pd.call(null,b,c,a,0)}return O};f.P=function(a,b){return b===this.u?this:sd?sd(this.ja,this.node,this.o,this.R,b):pd.call(null,this.ja,this.node,this.o,this.R,b)};f.T=function(a,b){return W(b,this)};
f.sb=function(){var a=this.o+this.node.length;if(a<la(this.ja)){var b=this.ja,c=fd(this.ja,a);return od?od(b,c,a,0):pd.call(null,b,c,a,0)}return null};rd.prototype[ja]=function(){return S(this)};
function pd(a){switch(arguments.length){case 3:var b=arguments[0],c=arguments[1],d=arguments[2];return new rd(b,gd(b,c),c,d,null);case 4:return od(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return sd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}function od(a,b,c,d){return new rd(a,b,c,d,null)}function sd(a,b,c,d,e){return new rd(a,b,c,d,e)}
function td(a,b){return a===b.D?b:new ad(a,C(b.i))}function md(a){return new ad({},C(a.i))}function nd(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];lc(a,0,b,0,a.length);return b}var ud=function ud(a,b,c,d){c=td(a.root.D,c);var g=a.m-1>>>b&31;if(5===b)a=d;else{var h=c.i[g];null!=h?(b-=5,a=ud.ea?ud.ea(a,b,h,d):ud.call(null,a,b,h,d)):a=dd(a.root.D,b-5,d)}c.i[g]=a;return c};
function ld(a,b,c,d){this.m=a;this.shift=b;this.root=c;this.da=d;this.A=88;this.j=275}f=ld.prototype;
f.$a=function(a,b){if(this.root.D){if(32>this.m-cd(this))this.da[this.m&31]=b;else{a=new ad(this.root.D,this.da);var c=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];c[0]=b;this.da=c;this.m>>>5>1<<this.shift?(b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],c=this.shift+
5,b[0]=this.root,b[1]=dd(this.root.D,this.shift,a),this.root=new ad(this.root.D,b),this.shift=c):this.root=ud(this,this.shift,this.root,a)}this.m+=1;return this}throw Error("conj! after persistent!");};f.ib=function(){if(this.root.D){this.root.D=null;var a=this.m-cd(this),b=Array(a);lc(this.da,0,b,0,a);return new Y(null,this.m,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Va=function(a,b,c){if("number"===typeof b)return vd(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
function vd(a,b,c){if(a.root.D){if(0<=b&&b<a.m){if(cd(a)<=b)a.da[b&31]=c;else{var d=function k(g,h){h=td(a.root.D,h);if(0===g)h.i[b&31]=c;else{var m=b>>>g&31;g=k(g-5,h.i[m]);h.i[m]=g}return h}(a.shift,a.root);a.root=d}return a}if(b===a.m)return a.$a(null,c);throw Error(["Index ",A.g(b)," out of bounds for TransientVector of length",A.g(a.m)].join(""));}throw Error("assoc! after persistent!");}f.U=function(){if(this.root.D)return this.m;throw Error("count after persistent!");};
f.W=function(a,b){if(this.root.D)return gd(this,b)[b&31];throw Error("nth after persistent!");};f.la=function(a,b,c){return 0<=b&&b<this.m?this.W(null,b):c};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){if(this.root.D)return"number"===typeof b?this.la(null,b,c):c;throw Error("lookup after persistent!");};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};function wd(){this.j=2097152;this.A=0}wd.prototype.J=function(){return!1};var xd=new wd;
function yd(a,b){return nc(hc(b)&&!ic(b)?U(a)===U(b)?(null!=a?a.j&1048576||v===a.Cb||(a.j?0:x(Ka,a)):x(Ka,a))?vc(function(c,d,e){return Q.h(yb(b,d,xd),e)?!0:new Jb},a):Yc(function(c){return Q.h(yb(b,N(c),xd),N(P(c)))},a):null:null)}function zd(a){this.C=a}zd.prototype.next=function(){if(null!=this.C){var a=N(this.C),b=$b(a,0,null);a=$b(a,1,null);this.C=P(this.C);return{value:[b,a],done:!1}}return{value:null,done:!0}};
function Ad(a,b){if(b instanceof I)a:{var c=a.length;b=b.va;for(var d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof I&&b===a[d].va){a=d;break a}d+=2}}else if("string"===typeof b||"number"===typeof b)a:for(c=a.length,d=0;;){if(c<=d){a=-1;break a}if(b===a[d]){a=d;break a}d+=2}else if(b instanceof vb)a:for(c=a.length,b=b.Aa,d=0;;){if(c<=d){a=-1;break a}if(a[d]instanceof vb&&b===a[d].Aa){a=d;break a}d+=2}else if(null==b)a:for(b=a.length,c=0;;){if(b<=c){a=-1;break a}if(null==a[c]){a=c;break a}c+=2}else a:for(c=
a.length,d=0;;){if(c<=d){a=-1;break a}if(Q.h(b,a[d])){a=d;break a}d+=2}return a}function Bd(a,b){this.key=a;this.G=b;this.v=null;this.j=166619935;this.A=0}f=Bd.prototype;f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.ka=function(a,b){return this.la(null,b,null)};f.H=function(a,b,c){return this.la(null,b,c)};f.W=function(a,b){if(0===b)return this.key;if(1===b)return this.G;throw Error("Index out of bounds");};
f.la=function(a,b,c){return 0===b?this.key:1===b?this.G:c};f.ob=function(a,b){return(new Y(null,2,5,qd,[this.key,this.G],null)).ob(a,b)};f.O=function(){return null};f.U=function(){return 2};f.Eb=function(){return this.key};f.Fb=function(){return this.G};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};f.V=function(){return null};
f.Z=function(a,b){a:if(a=this.U(null),0===a)b=b.F?b.F():b.call(null);else for(var c=this.W(null,0),d=1;;)if(d<a){var e=this.W(null,d);c=b.h?b.h(c,e):b.call(null,c,e);if(Kb(c)){b=Da(c);break a}d+=1}else{b=c;break a}return b};f.$=function(a,b,c){a:{a=this.U(null);var d=c;for(c=0;;)if(c<a){var e=this.W(null,c);d=b.h?b.h(d,e):b.call(null,d,e);if(Kb(d)){b=Da(d);break a}c+=1}else{b=d;break a}}return b};f.xa=function(a,b,c){return ac.l(new Y(null,2,5,qd,[this.key,this.G],null),b,c)};
f.Ua=function(a,b){return 0===b||1===b};f.I=function(){return new M([this.key,this.G],0,null)};f.P=function(a,b){return ec(new Y(null,2,5,qd,[this.key,this.G],null),b)};f.T=function(a,b){return new Y(null,3,5,qd,[this.key,this.G,b],null)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return this.W(null,a)};f.h=function(a,b){return this.la(null,a,b)};function Cd(a){return null!=a?a.j&2048||v===a.Ub?!0:!1:!1}function Dd(a,b,c){this.i=a;this.o=b;this.ra=c;this.j=32374990;this.A=262144}f=Dd.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){return this.o<this.i.length-2?new Dd(this.i,this.o+2,null):null};f.U=function(){return(this.i.length-this.o)/2};f.N=function(){return Fb(this)};f.J=function(a,b){return Ub(this,b)};
f.V=function(){return O};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return new Bd(this.i[this.o],this.i[this.o+1])};f.fa=function(){return this.o<this.i.length-2?new Dd(this.i,this.o+2,null):O};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new Dd(this.i,this.o,b)};f.T=function(a,b){return W(b,this)};Dd.prototype[ja]=function(){return S(this)};function Ed(a,b){this.i=a;this.o=0;this.m=b}
Ed.prototype.ia=function(){return this.o<this.m};Ed.prototype.next=function(){var a=new Bd(this.i[this.o],this.i[this.o+1]);this.o+=2;return a};function fb(a,b,c,d){this.u=a;this.m=b;this.i=c;this.v=d;this.j=16647951;this.A=401412}f=fb.prototype;f.toString=function(){return eb(this)};f.keys=function(){return S(Fd.g?Fd.g(this):Fd.call(null,this))};f.entries=function(){return new zd(K(K(this)))};f.values=function(){return S(Gd.g?Gd.g(this):Gd.call(null,this))};f.has=function(a){return oc(this,a)};
f.get=function(a,b){return this.H(null,a,b)};f.forEach=function(a){for(var b=K(this),c=null,d=0,e=0;;)if(e<d){var g=c.W(null,e),h=$b(g,0,null);g=$b(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=K(b))kc(b)?(c=$a(b),b=ab(b),h=c,d=U(c),c=h):(c=N(b),h=$b(c,0,null),g=$b(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){a=Ad(this.i,b);return-1===a?c:this.i[a+1]};
f.hb=function(a,b,c){a=this.i.length;for(var d=0;;)if(d<a){var e=this.i[d],g=this.i[d+1];c=b.l?b.l(c,e,g):b.call(null,c,e,g);if(Kb(c))return Da(c);d+=2}else return c};f.ta=function(){return new Ed(this.i,2*this.m)};f.O=function(){return this.u};f.U=function(){return this.m};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Hb(this)};
f.J=function(a,b){if(hc(b)&&!ic(b))if(a=this.i.length,this.m===b.U(null))for(var c=0;;)if(c<a){var d=b.H(null,this.i[c],mc);if(d!==mc)if(Q.h(this.i[c+1],d))c+=2;else return!1;else return!1}else return!0;else return!1;else return!1};f.Xa=function(){return new Hd(this.i.length,C(this.i))};f.V=function(){return Ga(Wc,this.u)};f.Z=function(a,b){return tc(this,b)};f.$=function(a,b,c){return uc(this,b,c)};
f.xa=function(a,b,c){a=Ad(this.i,b);if(-1===a){if(this.m<Id){a=this.i;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new fb(this.u,this.m+1,e,null)}return Ga(xa($c(Jd,this),b,c),this.u)}if(c===this.i[a+1])return this;b=C(this.i);b[a+1]=c;return new fb(this.u,this.m,b,null)};f.Ua=function(a,b){return-1!==Ad(this.i,b)};f.I=function(){var a=this.i;return 0<=a.length-2?new Dd(a,0,null):null};
f.P=function(a,b){return b===this.u?this:new fb(b,this.m,this.i,this.v)};f.T=function(a,b){if(jc(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=K(b);;){if(null==b)return a;var c=N(b);if(jc(c))a=xa(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var Wc=new fb(null,0,[],Ib),Id=8;function Kd(a,b){return a===b?!0:a===b||a instanceof I&&b instanceof I&&a.va===b.va?!0:Q.h(a,b)}
function Ld(a){for(var b=0,c=0;;)if(b<a.length){var d;a:for(d=0;;)if(d<b){var e=Kd(a[b],a[d]);if(e){d=e;break a}d=2+d}else{d=!1;break a}c=d?c:c+2;b=2+b}else return c}function Md(a,b){var c=a.length-1,d=K(b);b=Array(c+2*U(d));a=lc(a,0,b,0,c);for(b=c;;)if(d){var e=N(d);a[b]=Aa(e);a[b+1]=Ba(e);b=2+c;d=P(d)}else return a}
function bc(a){var b=a.length,c=1===(b&1),d;if(!(d=c))a:for(d=0;;)if(d<a.length){var e;b:for(e=0;;)if(e<d){var g=Kd(a[d],a[e]);if(g){e=g;break b}e=2+e}else{e=!1;break b}if(e){d=e;break a}d=2+d}else{d=!1;break a}return d?Nd(a,c):new fb(null,b/2,a,null)}
function Nd(a,b){var c=b?Md(a,$c(Wc,a[a.length-1])):a;a=Ld(c);var d=c.length;if(a<d){a=Array(a);for(var e=0,g=0;;)if(e<d)(function(){for(var h=0;;)if(h<g){var k=Kd(c[e],c[h]);if(k)return k;h=2+h}else return!1})()?(b=g,e=2+e,g=b):(b=function(){for(var h=d-2;;)if(h>=e){if(Kd(c[e],c[h]))return h;h-=2}else return h}(),a[g]=c[e],a[g+1]=c[b+1],b=2+g,e=2+e,g=b);else break;return new fb(null,a.length/2,a,null)}return new fb(null,c.length/2,c,null)}fb.prototype[ja]=function(){return S(this)};
function Hd(a,b){this.Wa={};this.Sa=a;this.i=b;this.j=259;this.A=56}f=Hd.prototype;f.U=function(){if(this.Wa)return xc(this.Sa);throw Error("count after persistent!");};f.ka=function(a,b){return this.H(null,b,null)};f.H=function(a,b,c){if(this.Wa)return a=Ad(this.i,b),-1===a?c:this.i[a+1];throw Error("lookup after persistent!");};
f.$a=function(a,b){if(this.Wa){if(Cd(b))return this.Va(null,Od.g?Od.g(b):Od.call(null,b),Pd.g?Pd.g(b):Pd.call(null,b));if(jc(b))return this.Va(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));a=K(b);for(b=this;;){var c=N(a);if(w(c))a=P(a),b=Ya(b,Od.g?Od.g(c):Od.call(null,c),Pd.g?Pd.g(c):Pd.call(null,c));else return b}}else throw Error("conj! after persistent!");};f.ib=function(){if(this.Wa)return this.Wa=!1,new fb(null,xc(this.Sa),this.i,null);throw Error("persistent! called twice");};
f.Va=function(a,b,c){if(this.Wa){a=Ad(this.i,b);if(-1===a){if(this.Sa+2<=2*Id)return this.Sa+=2,this.i.push(b),this.i.push(c),this;a=Qd.h?Qd.h(this.Sa,this.i):Qd.call(null,this.Sa,this.i);return Ya(a,b,c)}c!==this.i[a+1]&&(this.i[a+1]=c);return this}throw Error("assoc! after persistent!");};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};
f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.H(null,a,null)};f.h=function(a,b){return this.H(null,a,b)};function Qd(a,b){for(var c=Va(Jd),d=0;;)if(d<a)c=Ya(c,b[d],b[d+1]),d+=2;else return c}function Rd(){this.G=!1}function Sd(a,b,c){a=C(a);a[b]=c;return a}function Td(a,b,c,d){a=a.Ra(b);a.i[c]=d;return a}
function Vd(a,b,c){for(var d=a.length,e=0,g=c;;)if(e<d){c=a[e];if(null!=c){var h=a[e+1];c=b.l?b.l(g,c,h):b.call(null,g,c,h)}else c=a[e+1],c=null!=c?c.cb(b,g):g;if(Kb(c))return c;e+=2;g=c}else return g}function Wd(a){this.i=a;this.o=0;this.pa=this.eb=null}Wd.prototype.advance=function(){for(var a=this.i.length;;)if(this.o<a){var b=this.i[this.o],c=this.i[this.o+1];null!=b?b=this.eb=new Bd(b,c):null!=c?(b=cb(c),b=b.ia()?this.pa=b:!1):b=!1;this.o+=2;if(b)return!0}else return!1};
Wd.prototype.ia=function(){var a=null!=this.eb;return a?a:(a=null!=this.pa)?a:this.advance()};Wd.prototype.next=function(){if(null!=this.eb){var a=this.eb;this.eb=null;return a}if(null!=this.pa)return a=this.pa.next(),this.pa.ia()||(this.pa=null),a;if(this.advance())return this.next();throw Error("No such element");};Wd.prototype.remove=function(){return Error("Unsupported operation")};function Xd(a,b,c){this.D=a;this.M=b;this.i=c;this.A=131072;this.j=0}f=Xd.prototype;
f.Ra=function(a){if(a===this.D)return this;var b=yc(this.M),c=Array(0>b?4:2*(b+1));lc(this.i,0,c,0,2*b);return new Xd(a,this.M,c)};f.bb=function(){return Yd?Yd(this.i):Zd.call(null,this.i)};f.cb=function(a,b){return Vd(this.i,a,b)};f.za=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.M&e))return d;var g=yc(this.M&e-1);e=this.i[2*g];g=this.i[2*g+1];return null==e?g.za(a+5,b,c,d):Kd(c,e)?g:d};
f.na=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=yc(this.M&h-1);if(0===(this.M&h)){var m=yc(this.M);if(2*m<this.i.length){a=this.Ra(a);b=a.i;g.G=!0;c=2*(m-k);g=2*k+(c-1);for(m=2*(k+1)+(c-1);0!==c;)b[m]=b[g],--m,--c,--g;b[2*k]=d;b[2*k+1]=e;a.M|=h;return a}if(16<=m){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=$d.na(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0===(this.M>>>d&1)?
d+=1:(k[d]=null!=this.i[e]?$d.na(a,b+5,tb(this.i[e]),this.i[e],this.i[e+1],g):this.i[e+1],e+=2,d+=1);else break;return new ae(a,m+1,k)}b=Array(2*(m+4));lc(this.i,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;lc(this.i,2*k,b,2*(k+1),2*(m-k));g.G=!0;a=this.Ra(a);a.i=b;a.M|=h;return a}m=this.i[2*k];h=this.i[2*k+1];if(null==m)return m=h.na(a,b+5,c,d,e,g),m===h?this:Td(this,a,2*k+1,m);if(Kd(d,m))return e===h?this:Td(this,a,2*k+1,e);g.G=!0;g=b+5;d=be?be(a,g,m,h,c,d,e):ce.call(null,a,g,m,h,c,d,e);e=2*k;k=2*k+1;a=this.Ra(a);
a.i[e]=null;a.i[k]=d;return a};
f.ma=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=yc(this.M&g-1);if(0===(this.M&g)){var k=yc(this.M);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=$d.ma(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0===(this.M>>>c&1)?c+=1:(h[c]=null!=this.i[d]?$d.ma(a+5,tb(this.i[d]),this.i[d],this.i[d+1],e):this.i[d+1],d+=2,c+=1);else break;return new ae(null,k+1,h)}a=Array(2*(k+1));lc(this.i,
0,a,0,2*h);a[2*h]=c;a[2*h+1]=d;lc(this.i,2*h,a,2*(h+1),2*(k-h));e.G=!0;return new Xd(null,this.M|g,a)}var m=this.i[2*h];g=this.i[2*h+1];if(null==m)return k=g.ma(a+5,b,c,d,e),k===g?this:new Xd(null,this.M,Sd(this.i,2*h+1,k));if(Kd(c,m))return d===g?this:new Xd(null,this.M,Sd(this.i,2*h+1,d));e.G=!0;e=this.M;k=this.i;a+=5;a=de?de(a,m,g,b,c,d):ce.call(null,a,m,g,b,c,d);c=2*h;h=2*h+1;d=C(k);d[c]=null;d[h]=a;return new Xd(null,e,d)};f.ta=function(){return new Wd(this.i)};var $d=new Xd(null,0,[]);
function ee(a){this.i=a;this.o=0;this.pa=null}ee.prototype.ia=function(){for(var a=this.i.length;;){if(null!=this.pa&&this.pa.ia())return!0;if(this.o<a){var b=this.i[this.o];this.o+=1;null!=b&&(this.pa=cb(b))}else return!1}};ee.prototype.next=function(){if(this.ia())return this.pa.next();throw Error("No such element");};ee.prototype.remove=function(){return Error("Unsupported operation")};function ae(a,b,c){this.D=a;this.m=b;this.i=c;this.A=131072;this.j=0}f=ae.prototype;
f.Ra=function(a){return a===this.D?this:new ae(a,this.m,C(this.i))};f.bb=function(){return fe?fe(this.i):ge.call(null,this.i)};f.cb=function(a,b){for(var c=this.i.length,d=0;;)if(d<c){var e=this.i[d];if(null!=e){b=e.cb(a,b);if(Kb(b))return b;d+=1}else d+=1}else return b};f.za=function(a,b,c,d){var e=this.i[b>>>a&31];return null!=e?e.za(a+5,b,c,d):d};
f.na=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.i[h];if(null==k)return a=Td(this,a,h,$d.na(a,b+5,c,d,e,g)),a.m+=1,a;b=k.na(a,b+5,c,d,e,g);return b===k?this:Td(this,a,h,b)};f.ma=function(a,b,c,d,e){var g=b>>>a&31,h=this.i[g];if(null==h)return new ae(null,this.m+1,Sd(this.i,g,$d.ma(a+5,b,c,d,e)));a=h.ma(a+5,b,c,d,e);return a===h?this:new ae(null,this.m,Sd(this.i,g,a))};f.ta=function(){return new ee(this.i)};function he(a,b,c){b*=2;for(var d=0;;)if(d<b){if(Kd(c,a[d]))return d;d+=2}else return-1}
function ie(a,b,c,d){this.D=a;this.ya=b;this.m=c;this.i=d;this.A=131072;this.j=0}f=ie.prototype;f.Ra=function(a){if(a===this.D)return this;var b=Array(2*(this.m+1));lc(this.i,0,b,0,2*this.m);return new ie(a,this.ya,this.m,b)};f.bb=function(){return Yd?Yd(this.i):Zd.call(null,this.i)};f.cb=function(a,b){return Vd(this.i,a,b)};f.za=function(a,b,c,d){a=he(this.i,this.m,c);return 0>a?d:Kd(c,this.i[a])?this.i[a+1]:d};
f.na=function(a,b,c,d,e,g){if(c===this.ya){b=he(this.i,this.m,d);if(-1===b){if(this.i.length>2*this.m)return b=2*this.m,c=2*this.m+1,a=this.Ra(a),a.i[b]=d,a.i[c]=e,g.G=!0,a.m+=1,a;c=this.i.length;b=Array(c+2);lc(this.i,0,b,0,c);b[c]=d;b[c+1]=e;g.G=!0;d=this.m+1;a===this.D?(this.i=b,this.m=d,a=this):a=new ie(this.D,this.ya,d,b);return a}return this.i[b+1]===e?this:Td(this,a,b+1,e)}return(new Xd(a,1<<(this.ya>>>b&31),[null,this,null,null])).na(a,b,c,d,e,g)};
f.ma=function(a,b,c,d,e){return b===this.ya?(a=he(this.i,this.m,c),-1===a?(a=2*this.m,b=Array(a+2),lc(this.i,0,b,0,a),b[a]=c,b[a+1]=d,e.G=!0,new ie(null,this.ya,this.m+1,b)):Q.h(this.i[a+1],d)?this:new ie(null,this.ya,this.m,Sd(this.i,a+1,d))):(new Xd(null,1<<(this.ya>>>a&31),[null,this])).ma(a,b,c,d,e)};f.ta=function(){return new Wd(this.i)};
function ce(a){switch(arguments.length){case 6:return de(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return be(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}function de(a,b,c,d,e,g){var h=tb(b);if(h===d)return new ie(null,h,2,[b,c,e,g]);var k=new Rd;return $d.ma(a,h,b,c,k).ma(a,d,e,g,k)}
function be(a,b,c,d,e,g,h){var k=tb(c);if(k===e)return new ie(null,k,2,[c,d,g,h]);var m=new Rd;return $d.na(a,b,k,c,d,m).na(a,b,e,g,h,m)}function je(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0}f=je.prototype;f.toString=function(){return eb(this)};
f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){if(null==this.C){var a=this.qa,b=this.o+2;return ke?ke(a,b,null):Zd.call(null,a,b,null)}a=this.qa;b=this.o;var c=P(this.C);return ke?ke(a,b,c):Zd.call(null,a,b,c)};
f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return null==this.C?new Bd(this.qa[this.o],this.qa[this.o+1]):N(this.C)};
f.fa=function(){var a=this,b=null==a.C?function(){var c=a.qa,d=a.o+2;return ke?ke(c,d,null):Zd.call(null,c,d,null)}():function(){var c=a.qa,d=a.o,e=P(a.C);return ke?ke(c,d,e):Zd.call(null,c,d,e)}();return null!=b?b:O};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new je(b,this.qa,this.o,this.C,this.v)};f.T=function(a,b){return W(b,this)};je.prototype[ja]=function(){return S(this)};
function Zd(a){switch(arguments.length){case 1:return Yd(arguments[0]);case 3:return ke(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}function Yd(a){return ke(a,0,null)}function ke(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new je(null,a,b,null,null);var d=a[b+1];if(w(d)&&(d=d.bb(),w(d)))return new je(null,a,b+2,d,null);b+=2}else return null;else return new je(null,a,b,c,null)}
function le(a,b,c,d,e){this.u=a;this.qa=b;this.o=c;this.C=d;this.v=e;this.j=32374988;this.A=0}f=le.prototype;f.toString=function(){return eb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.u};f.X=function(){var a=this.qa,b=this.o,c=P(this.C);return me?me(a,b,c):ge.call(null,a,b,c)};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Fb(this)};f.J=function(a,b){return Ub(this,b)};
f.V=function(){return O};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return N(this.C)};f.fa=function(){var a=this.qa;var b=this.o,c=P(this.C);a=me?me(a,b,c):ge.call(null,a,b,c);return null!=a?a:O};f.I=function(){return this};f.P=function(a,b){return b===this.u?this:new le(b,this.qa,this.o,this.C,this.v)};f.T=function(a,b){return W(b,this)};le.prototype[ja]=function(){return S(this)};
function ge(a){switch(arguments.length){case 1:return fe(arguments[0]);case 3:return me(arguments[0],arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length)].join(""));}}function fe(a){return me(a,0,null)}function me(a,b,c){if(null==c)for(c=a.length;;)if(b<c){var d=a[b];if(w(d)&&(d=d.bb(),w(d)))return new le(null,a,b+1,d,null);b+=1}else return null;else return new le(null,a,b,c,null)}function ne(a,b){this.ca=a;this.xb=b;this.qb=!1}
ne.prototype.ia=function(){return!this.qb||this.xb.ia()};ne.prototype.next=function(){if(this.qb)return this.xb.next();this.qb=!0;return new Bd(null,this.ca)};ne.prototype.remove=function(){return Error("Unsupported operation")};function oe(a,b,c,d,e,g){this.u=a;this.m=b;this.root=c;this.ha=d;this.ca=e;this.v=g;this.j=16123663;this.A=139268}f=oe.prototype;f.toString=function(){return eb(this)};f.keys=function(){return S(Fd.g?Fd.g(this):Fd.call(null,this))};f.entries=function(){return new zd(K(K(this)))};
f.values=function(){return S(Gd.g?Gd.g(this):Gd.call(null,this))};f.has=function(a){return oc(this,a)};f.get=function(a,b){return this.H(null,a,b)};f.forEach=function(a){for(var b=K(this),c=null,d=0,e=0;;)if(e<d){var g=c.W(null,e),h=$b(g,0,null);g=$b(g,1,null);a.h?a.h(g,h):a.call(null,g,h);e+=1}else if(b=K(b))kc(b)?(c=$a(b),b=ab(b),h=c,d=U(c),c=h):(c=N(b),h=$b(c,0,null),g=$b(c,1,null),a.h?a.h(g,h):a.call(null,g,h),b=P(b),c=null,d=0),e=0;else return null};f.ka=function(a,b){return this.H(null,b,null)};
f.H=function(a,b,c){return null==b?this.ha?this.ca:c:null==this.root?c:this.root.za(0,tb(b),b,c)};f.hb=function(a,b,c){a=this.ha?b.l?b.l(c,null,this.ca):b.call(null,c,null,this.ca):c;Kb(a)?b=Da(a):null!=this.root?(b=this.root.cb(b,a),b=Kb(b)?Lb.g?Lb.g(b):Lb.call(null,b):b):b=a;return b};f.ta=function(){var a=this.root?cb(this.root):new Xc(Wc);return this.ha?new ne(this.ca,a):a};f.O=function(){return this.u};f.U=function(){return this.m};f.N=function(){var a=this.v;return null!=a?a:this.v=a=Hb(this)};
f.J=function(a,b){return yd(this,b)};f.Xa=function(){return new pe(this.root,this.m,this.ha,this.ca)};f.V=function(){return Ga(Jd,this.u)};f.xa=function(a,b,c){if(null==b)return this.ha&&c===this.ca?this:new oe(this.u,this.ha?this.m:this.m+1,this.root,!0,c,null);a=new Rd;b=(null==this.root?$d:this.root).ma(0,tb(b),b,c,a);return b===this.root?this:new oe(this.u,a.G?this.m+1:this.m,b,this.ha,this.ca,null)};f.Ua=function(a,b){return null==b?this.ha:null==this.root?!1:this.root.za(0,tb(b),b,mc)!==mc};
f.I=function(){if(0<this.m){var a=null!=this.root?this.root.bb():null;return this.ha?W(new Bd(null,this.ca),a):a}return null};f.P=function(a,b){return b===this.u?this:new oe(b,this.m,this.root,this.ha,this.ca,this.v)};f.T=function(a,b){if(jc(b))return this.xa(null,D(b,0),D(b,1));a=this;for(b=K(b);;){if(null==b)return a;var c=N(b);if(jc(c))a=xa(a,D(c,0),D(c,1)),b=P(b);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};var Jd=new oe(null,0,null,!1,null,Ib);oe.prototype[ja]=function(){return S(this)};
function pe(a,b,c,d){this.D={};this.root=a;this.count=b;this.ha=c;this.ca=d;this.j=259;this.A=56}function qe(a,b,c){if(a.D){if(null==b)a.ca!==c&&(a.ca=c),a.ha||(a.count+=1,a.ha=!0);else{var d=new Rd;b=(null==a.root?$d:a.root).na(a.D,0,tb(b),b,c,d);b!==a.root&&(a.root=b);d.G&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=pe.prototype;f.U=function(){if(this.D)return this.count;throw Error("count after persistent!");};
f.ka=function(a,b){return null==b?this.ha?this.ca:null:null==this.root?null:this.root.za(0,tb(b),b)};f.H=function(a,b,c){return null==b?this.ha?this.ca:c:null==this.root?c:this.root.za(0,tb(b),b,c)};
f.$a=function(a,b){a:if(this.D)if(Cd(b))a=qe(this,Od.g?Od.g(b):Od.call(null,b),Pd.g?Pd.g(b):Pd.call(null,b));else if(jc(b))a=qe(this,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=K(b),b=this;;){var c=N(a);if(w(c))a=P(a),b=qe(b,Od.g?Od.g(c):Od.call(null,c),Pd.g?Pd.g(c):Pd.call(null,c));else{a=b;break a}}else throw Error("conj! after persistent");return a};
f.ib=function(){if(this.D){this.D=null;var a=new oe(null,this.count,this.root,this.ha,this.ca,null)}else throw Error("persistent! called twice");return a};f.Va=function(a,b,c){return qe(this,b,c)};f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",A.g(arguments.length-1)].join(""));}};f.apply=function(a,b){return this.call.apply(this,[this].concat(C(b)))};
f.g=function(a){return this.ka(null,a)};f.h=function(a,b){return this.H(null,a,b)};function re(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}f=re.prototype;f.toString=function(){return eb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){var a=(null!=this.B?this.B.j&128||v===this.B.Ya||(this.B.j?0:x(ra,this.B)):x(ra,this.B))?this.B.X():P(this.B);return null==a?null:new re(a,null)};f.N=function(){return Fb(this)};
f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return this.B.aa(null).key};f.fa=function(){var a=(null!=this.B?this.B.j&128||v===this.B.Ya||(this.B.j?0:x(ra,this.B)):x(ra,this.B))?this.B.X():P(this.B);return null!=a?new re(a,null):O};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new re(this.B,b)};f.T=function(a,b){return W(b,this)};re.prototype[ja]=function(){return S(this)};
function Fd(a){return(a=K(a))?new re(a,null):null}function Od(a){return Aa(a)}function se(a,b){this.B=a;this.ra=b;this.j=32374988;this.A=0}f=se.prototype;f.toString=function(){return eb(this)};f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return T(this,b,0);case 2:return T(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return T(this,b,0)};a.h=function(b,c){return T(this,b,c)};return a}();
f.lastIndexOf=function(){function a(c){return V(this,c,U(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return V(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return V(this,c,d)};return b}();f.O=function(){return this.ra};f.X=function(){var a=(null!=this.B?this.B.j&128||v===this.B.Ya||(this.B.j?0:x(ra,this.B)):x(ra,this.B))?this.B.X():P(this.B);return null==a?null:new se(a,null)};f.N=function(){return Fb(this)};
f.J=function(a,b){return Ub(this,b)};f.V=function(){return O};f.Z=function(a,b){return pc(b,this)};f.$=function(a,b,c){return sc(b,c,this)};f.aa=function(){return this.B.aa(null).G};f.fa=function(){var a=(null!=this.B?this.B.j&128||v===this.B.Ya||(this.B.j?0:x(ra,this.B)):x(ra,this.B))?this.B.X():P(this.B);return null!=a?new se(a,null):O};f.I=function(){return this};f.P=function(a,b){return b===this.ra?this:new se(this.B,b)};f.T=function(a,b){return W(b,this)};se.prototype[ja]=function(){return S(this)};
function Gd(a){return(a=K(a))?new se(a,null):null}function Pd(a){return Ba(a)}function Dc(a){if(null!=a&&(a.A&4096||v===a.Hb))return a.name;if("string"===typeof a)return a;throw Error(["Doesn't support name: ",A.g(a)].join(""));}function te(a){a:for(var b=a;;)if(b=K(b))b=P(b);else break a;return a}
function ue(a,b,c,d,e,g,h){var k=fa;fa=null==fa?null:fa-1;try{if(null!=fa&&0>fa)return H(a,"#");H(a,c);if(0===kb.g(g))K(h)&&H(a,function(){var r=ve.g(g);return w(r)?r:"..."}());else{if(K(h)){var m=N(h);b.l?b.l(m,a,g):b.call(null,m,a,g)}for(var l=P(h),n=kb.g(g)-1;;)if(!l||null!=n&&0===n){K(l)&&0===n&&(H(a,d),H(a,function(){var r=ve.g(g);return w(r)?r:"..."}()));break}else{H(a,d);var p=N(l);c=a;h=g;b.l?b.l(p,c,h):b.call(null,p,c,h);var q=P(l);c=n-1;l=q;n=c}}return H(a,e)}finally{fa=k}}
function we(a,b){b=K(b);for(var c=null,d=0,e=0;;)if(e<d){var g=c.W(null,e);H(a,g);e+=1}else if(b=K(b))c=b,kc(c)?(b=$a(c),d=ab(c),c=b,g=U(b),b=d,d=g):(g=N(c),H(a,g),b=P(c),c=null,d=0),e=0;else return null}var xe={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function ye(a){return['"',A.g(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(b){return xe[b]})),'"'].join("")}
function ze(a,b){return(a=nc(wb(a,ib)))?(a=null!=b?b.j&131072||v===b.Gb?!0:!1:!1)?null!=fc(b):a:a}
function Ae(a,b,c){if(null==a)return H(b,"nil");if(ze(c,a)){H(b,"^");var d=fc(a);Z.l?Z.l(d,b,c):Z.call(null,d,b,c);H(b," ")}if(a.Kb)return a.Xb(a,b,c);if(null!=a?a.j&2147483648||v===a.Y||(a.j?0:x(Ta,a)):x(Ta,a))return Ua(a,b,c);if(!0===a||!1===a)return H(b,A.g(a));if("number"===typeof a)return H(b,isNaN(a)?"##NaN":a===Number.POSITIVE_INFINITY?"##Inf":a===Number.NEGATIVE_INFINITY?"##-Inf":A.g(a));if(null!=a&&a.constructor===Object)return H(b,"#js "),d=X.h(function(g){var h=/[A-Za-z_\*\+\?!\-'][\w\*\+\?!\-']*/;
if("string"===typeof g)if(h=h.exec(g),null!=h&&Q.h(h[0],g))if(1===h.length)h=h[0];else if(w(Cd.g?Cd.g(h):Cd.call(null,h)))h=new Y(null,2,5,qd,[Od.g?Od.g(h):Od.call(null,h),Pd.g?Pd.g(h):Pd.call(null,h)],null);else if(jc(h))h=ec(h,null);else if(ha(h))b:{var k=h.length;if(32>k)h=new Y(null,k,5,qd,h,null);else for(var m=32,l=(new Y(null,32,5,qd,h.slice(0,32),null)).Xa(null);;)if(m<k){var n=m+1;l=Wa(l,h[m]);m=n}else{h=Xa(l);break b}}else h=Xa(qc(Wa,Va(Xb),h));else h=null;else throw new TypeError("re-matches must match against a string.");
return new Bd(null!=h?Cc.g(g):g,a[g])},da(a)),Be.ea?Be.ea(d,Z,b,c):Be.call(null,d,Z,b,c);if(ha(a))return ue(b,Z,"#js ["," ","]",c,a);if("string"===typeof a)return w(hb.g(c))?H(b,ye(a)):H(b,a);if("function"===typeof a){var e=a.name;c=w(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Function":e;return we(b,Vb(["#object[",c,w(!1)?[' "',A.g(a),'"'].join(""):"","]"]))}if(a instanceof Date)return c=function(g,h){for(g=A.g(g);;)if(g.length<h)g=["0",g].join("");else return g},we(b,Vb(['#inst "',
c(a.getUTCFullYear(),4),"-",c(a.getUTCMonth()+1,2),"-",c(a.getUTCDate(),2),"T",c(a.getUTCHours(),2),":",c(a.getUTCMinutes(),2),":",c(a.getUTCSeconds(),2),".",c(a.getUTCMilliseconds(),3),"-",'00:00"']));if(a instanceof RegExp)return we(b,Vb(['#"',a.source,'"']));if("symbol"===t(a)||"undefined"!==typeof Symbol&&a instanceof Symbol)return we(b,Vb(["#object[",a.toString(),"]"]));if(w(function(){var g=null==a?null:a.constructor;return null==g?null:g.pb}()))return we(b,Vb(["#object[",a.constructor.pb.replace(RegExp("/",
"g"),"."),"]"]));e=function(){var g=null==a?null:a.constructor;return null==g?null:g.name}();c=w(function(){var g=null==e;return g?g:/^[\s\xa0]*$/.test(e)}())?"Object":e;return null==a.constructor?we(b,Vb(["#object[",c,"]"])):we(b,Vb(["#object[",c," ",A.g(a),"]"]))}function Z(a,b,c){var d=Ce.g(c);return w(d)?(c=ac.l(c,De,Ae),d.l?d.l(a,b,c):d.call(null,a,b,c)):Ae(a,b,c)}function Ee(a){return a instanceof vb?zb.h(null,Dc(a)):Cc.h(null,Dc(a))}
function Fe(a){if(w(!1)){var b=K(a),c=K(b),d=N(c);P(c);$b(d,0,null);$b(d,1,null);c=null==a?null:null!=a&&(a.j&4||v===a.Bb)?a.V(null):(null!=a?a.j&4||v===a.Bb||(a.j?0:x(ma,a)):x(ma,a))?na(a):null;for(a=null;;){d=a;b=K(b);a=N(b);var e=P(b),g=a;a=$b(g,0,null);b=$b(g,1,null);if(w(g))if(a instanceof I||a instanceof vb)if(w(d))if(Q.h(d,Bc(a)))c=ac.l(c,Ee(a),b),a=d,b=e;else return null;else if(d=Bc(a),w(d))c=ac.l(c,Ee(a),b),a=d,b=e;else return null;else return null;else return new Y(null,2,5,qd,[d,c],null)}}else return null}
function Ge(a,b,c,d,e){return ue(d,function(g,h,k){var m=Aa(g);c.l?c.l(m,h,k):c.call(null,m,h,k);H(h," ");g=Ba(g);return c.l?c.l(g,h,k):c.call(null,g,h,k)},[A.g(a),"{"].join(""),", ","}",e,K(b))}function Be(a,b,c,d){var e=hc(a)?Fe(a):null,g=$b(e,0,null);e=$b(e,1,null);return w(g)?Ge(["#:",A.g(g)].join(""),e,b,c,d):Ge(null,a,b,c,d)}M.prototype.Y=v;M.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Ec.prototype.Y=v;Ec.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};
Bd.prototype.Y=v;Bd.prototype.K=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};je.prototype.Y=v;je.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Dd.prototype.Y=v;Dd.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Eb.prototype.Y=v;Eb.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};rd.prototype.Y=v;rd.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Ac.prototype.Y=v;Ac.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};
oe.prototype.Y=v;oe.prototype.K=function(a,b,c){return Be(this,Z,b,c)};le.prototype.Y=v;le.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Ic.prototype.Y=v;Ic.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};se.prototype.Y=v;se.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Y.prototype.Y=v;Y.prototype.K=function(a,b,c){return ue(b,Z,"["," ","]",c,this)};zc.prototype.Y=v;zc.prototype.K=function(a,b){return H(b,"()")};fb.prototype.Y=v;
fb.prototype.K=function(a,b,c){return Be(this,Z,b,c)};re.prototype.Y=v;re.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};Yb.prototype.Y=v;Yb.prototype.K=function(a,b,c){return ue(b,Z,"("," ",")",c,this)};var ib=new I(null,"meta","meta",1499536964),kb=new I(null,"print-length","print-length",1931866356),He=new I(null,"mesh","mesh",456320595),gb=new I(null,"flush-on-newline","flush-on-newline",-151457939),jb=new I(null,"dup","dup",556298533),Ie=new I(null,"collider","collider",-1051727848),hb=new I(null,"readably","readably",1129599760),Je=new I(null,"rigid-body","rigid-body",95622460),Ke=new I(null,"renderer","renderer",336841071),De=new I(null,"fallback-impl","fallback-impl",-1501286995),Le=new I(null,
"camera","camera",-1190348585),ve=new I(null,"more-marker","more-marker",-14717935),Ce=new I(null,"alt-impl","alt-impl",670969595),Me=new I(null,"scene","scene",1523800415);var Ne=shadow$bridge("@dimforge/rapier3d-compat");var Oe=shadow$bridge("three/addons/controls/OrbitControls.js");var Pe=shadow$bridge("three/addons/environments/RoomEnvironment.js");var Qe=shadow$bridge("three/addons/loaders/GLTFLoader.js");var Re=shadow$bridge("three");var Se,Te=document.getElementById("app");Te.innerHTML="";var Ue=window.innerWidth,Ve=window.innerHeight,We=new Re.Scene,Xe=new Re.PerspectiveCamera(75,Ue/Ve,.1,1E3),Ye=new Re.WebGLRenderer,Ze=new Pe.RoomEnvironment,$e=(new Re.PMREMGenerator(Ye)).fromScene(Ze);We.background=new Re.Color(12303291);We.environment=$e.texture;Ye.toneMapping=Re.ACESFilmicToneMapping;Ye.toneMappingExposure=.3;Ye.setSize(Ue,Ve);Te.appendChild(Ye.domElement);Xe.position.set(0,5,-10);new Oe.OrbitControls(Xe,Ye.domElement);
Se=new fb(null,3,[Me,We,Le,Xe,Ke,Ye],null);function af(){var a=new Qe.GLTFLoader;return new Promise(function(b,c){return a.load("assets/test-scene.glb",function(d){return b.g?b.g(d):b.call(null,d)},function(d){return console.log([A.g(d.loaded/d.total*100),"% loaded"].join(""))},function(d){return c.g?c.g(d):c.call(null,d)})})}function bf(a,b){var c=b.translation();b=b.rotation();a.position.set(c.x,c.y,c.z);a.setRotationFromQuaternion(new Re.Quaternion(b.x,b.y,b.z,b.w));a.updateMatrix()}
function cf(a){a=a.clone();a.setRotationFromEuler(new Re.Euler(0,0,0));a.updateMatrixWorld();return a}
Ne.init().then(function(){var a=Vc(Se),b=wb(a,Me),c=wb(a,Le),d=wb(a,Ke),e=new Ne.World({x:0,y:-9.81,z:0});a=new Re.LineBasicMaterial({color:16777215,vertexColors:!0});var g=new Re.BufferGeometry,h=new Re.LineSegments(g,a);b.add(h);return af().then(function(k){b.add(k.scene);k.scene.updateMatrixWorld(!0);var m=te(Zc(function(l){var n=l.userData;n=new Y(null,2,5,qd,[n.collider_type,n.collider_shape],null);if(Q.h(new Y(null,2,5,qd,["static","box"],null),n)){l.geometry.computeBoundingBox();n=cf(l);var p=
(new Re.Box3).setFromObject(n).getSize(new Re.Vector3);n=p.x/2;var q=p.y/2,r=p.z/2;p=l.position.x;var u=l.position.y,z=l.position.z,B=Ne.ColliderDesc.cuboid;n=B.l?B.l(n,q,r):B.call(null,n,q,r);n=e.createCollider(n.setTranslation(p,u,z).setRotation({x:l.quaternion.x,y:l.quaternion.y,z:l.quaternion.z,w:l.quaternion.w}));bf(l,n);l=new fb(null,2,[He,l,Ie,n],null)}else Q.h(new Y(null,2,5,qd,["dynamic","box"],null),n)?(l.geometry.computeBoundingBox(),n=cf(l),p=(new Re.Box3).setFromObject(n).getSize(new Re.Vector3),
n=p.x/2,q=p.y/2,p=p.z/2,u=l.position.x,z=l.position.y,r=l.position.z,B=Ne.RigidBodyDesc.dynamic(),u=e.createRigidBody(B.setTranslation(u,z,r).setRotation({x:l.quaternion.x,y:l.quaternion.y,z:l.quaternion.z,w:l.quaternion.w})),z=Ne.ColliderDesc.cuboid,n=z.l?z.l(n,q,p):z.call(null,n,q,p),n=e.createCollider(n,u),bf(l,n),l=new fb(null,3,[He,l,Ie,n,Je,u],null)):Q.h(new Y(null,2,5,qd,["dynamic","sphere"],null),n)?(l.geometry.computeBoundingSphere(),n=l.geometry.boundingSphere.radius,q=l.position.x,p=l.position.y,
u=l.position.z,q=Ne.RigidBodyDesc.dynamic().setTranslation(q,p,u),q=e.createRigidBody(q),p=Ne.ColliderDesc.ball,n=p.g?p.g(n):p.call(null,n),n=e.createCollider(n.setRestitution(.5),q),bf(l,n),l=new fb(null,3,[He,l,Ie,n,Je,q],null)):l=null;return l},k.scene.children));return d.setAnimationLoop(function(){for(var l=K(m),n=null,p=0,q=0;;)if(q<p){var r=n.W(null,q),u=Vc(r);r=wb(u,He);u=wb(u,Ie);bf(r,u);q+=1}else if(l=K(l))kc(l)?(p=$a(l),l=ab(l),n=p,p=U(p)):(n=N(l),p=Vc(n),n=wb(p,He),p=wb(p,Ie),bf(n,p),
l=P(l),n=null,p=0),q=0;else break;l=e.debugRender();h.geometry.setAttribute("position",new Re.BufferAttribute(l.vertices,3));h.geometry.setAttribute("color",new Re.BufferAttribute(l.colors,4));e.step();return d.render(b,c)})})});
}).call(this);